from django.forms import ModelForm
from django import forms
from ppu.models import Ppu


class FormPpu(ModelForm):
    class Meta:
        model = Ppu
        fields = '__all__'
        pilihankota = (
            ('PPU', 'PPU'),
        )
        pilihankecamatan = (
            ('', ''),
            ('BABULU', 'BABULU'),
            ('PENAJAM', 'PENAJAM'),
            ('SEPAKU', 'SEPAKU'),
            ('WARU', 'WARU'),
        )
        pilihankelurahan = (
            ('', ''),
            ('BABULU DARAT', 'BABULU DARAT'),
            ('BABULU LAUT', 'BABULU LAUT'),
            ('GUNUNG INTAN', 'GUNUNG INTAN'),
            ('GUNUNG MAKMUR', 'GUNUNG MAKMUR'),
            ('GUNUNG MULIA', 'GUNUNG MULIA'),
            ('LABANGKA', 'LABANGKA'),
            ('LABANGKA BARAT', 'LABANGKA BARAT'),
            ('RAWA MULIA', 'RAWA MULIA'),
            ('RINTIK', 'RINTIK'),
            ('SEBAKUNG JAYA', 'SEBAKUNG JAYA'),
            ('SRI RAHARJA', 'SRI RAHARJA'),
            ('BUKIT SUBUR', 'BUKIT SUBUR'),
            ('BULUMINUNG', 'BULUMINUNG'),
            ('GERSIK', 'GERSIK'),
            ('GIRI MUKTI', 'GIRI MUKTI'),
            ('GIRIPURWA', 'GIRIPURWA'),
            ('GUNUNG SETELENG', 'GUNUNG SETELENG'),
            ('JENEBORA', 'JENEBORA'),
            ('LAWE-LAWE', 'LAWE-LAWE'),
            ('NENANG', 'NENANG'),
            ('NIPAH-NIPAH', 'NIPAH-NIPAH'),
            ('PANTAI LANGO', 'PANTAI LANGO'),
            ('PEJALA', 'PEJALA'),
            ('PENAJAM', 'PENAJAM'),
            ('PETUNG', 'PETUNG'),
            ('RIKO', 'RIKO'),
            ('SALO LOANG', 'SALO LOANG'),
            ('SEPAN', 'SEPAN'),
            ('SESUMPU', 'SESUMPU'),
            ('SIDOREJO', 'SIDOREJO'),
            ('SOTEK', 'SOTEK'),
            ('SUNGAI PARIT', 'SUNGAI PARIT'),
            ('TANJUNG TENGAH', 'TANJUNG TENGAH'),
            ('ARGO MULYO', 'ARGO MULYO'),
            ('BINUANG', 'BINUANG'),
            ('BUMI HARAPAN', 'BUMI HARAPAN'),
            ('KARANG JINAWI', 'KARANG JINAWI'),
            ('MARIDAN', 'MARIDAN'),
            ('MENTAWIR', 'MENTAWIR'),
            ('PEMALUAN', 'PEMALUAN'),
            ('SEMOI DUA', 'SEMOI DUA'),
            ('SEPAKU', 'SEPAKU'),
            ('SUKA RAJA', 'SUKA RAJA'),
            ('SUKO MULYO', 'SUKO MULYO'),
            ('TELEMOW', 'TELEMOW'),
            ('TENGIN BARU', 'TENGIN BARU'),
            ('WONO SARI', 'WONO SARI'),
            ('BANGUN MULYA', 'BANGUN MULYA'),
            ('SESULU', 'SESULU'),
            ('WARU', 'WARU'),
        )
        widgets = {
            # 'judul': forms.TextInput({'class': 'form-control'}),
            # 'penulis': forms.TextInput({'class': 'form-control'}),
            # 'penerbit': forms.TextInput({'class': 'form-control'}),
            # 'jumlah': forms.NumberInput({'class': 'form-control'}),
            # 'kelompok_id': forms.Select({'class': 'form-control'}),
            'nama_dpt': forms.TextInput({'class': 'form-control'}),
            'kota': forms.Select({'class': 'form-control'}, choices=pilihankota),
            'kecamatan': forms.Select({'class': 'form-control'}, choices=pilihankecamatan),
            'kelurahan': forms.Select({'class': 'form-control'}, choices=pilihankelurahan),
            'alamat': forms.TextInput({'class': 'form-control'}),
            'nik': forms.NumberInput({'class': 'form-control'}),
            'nomor_hp': forms.NumberInput({'class': 'form-control'}),
            'nomor_rekening': forms.NumberInput({'class': 'form-control'}),
            'nomor_kk': forms.NumberInput({'class': 'form-control'}),
            'tanggal_lahir': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_input_data': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_honor': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_telespocheck': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'rt': forms.NumberInput({'class': 'form-control'}),
            'nominal_honor': forms.NumberInput({'class': 'form-control'}),
            'bank': forms.TextInput({'class': 'form-control'}),
            'status_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan_telespocheck': forms.TextInput({'class': 'form-control'}),
            'telespochecker': forms.Select({'class': 'form-control'}),
            'hasil_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan': forms.TextInput({'class': 'form-control'}),
            'nama_pemilik_rekening': forms.TextInput({'class': 'form-control'}),
            'inputer': forms.Select({'class': 'form-control'}),
            'keterangan_honor': forms.TextInput({'class': 'form-control'}),
        }
