from django.forms import ModelForm
from django import forms
from kutim.models import Kutim


class FormKutim(ModelForm):
    class Meta:
        model = Kutim
        fields = '__all__'
        pilihankota = (
            ('KUTAI TIMUR', 'KUTAI TIMUR'),
        )
        pilihankecamatan = (
            ('', ''),
            ('BATU AMPAR', 'BATU AMPAR'),
            ('BENGALON', 'BENGALON'),
            ('BUSANG', 'BUSANG'),
            ('KALIORANG', 'KALIORANG'),
            ('KARANGAN', 'KARANGAN'),
            ('KAUBUN', 'KAUBUN'),
            ('KOMBENG', 'KOMBENG'),
            ('LONG MESANGAT', 'LONG MESANGAT'),
            ('MUARA ANCALONG', 'MUARA ANCALONG'),
            ('MUARA BENGKAL', 'MUARA BENGKAL'),
            ('MUARA WAHAU', 'MUARA WAHAU'),
            ('RANTAU PULUNG', 'RANTAU PULUNG'),
            ('SANDARAN', 'SANDARAN'),
            ('SANGATTA SELATAN', 'SANGATTA SELATAN'),
            ('SANGATTA UTARA', 'SANGATTA UTARA'),
            ('SANGKULIRANG', 'SANGKULIRANG'),
            ('TELEN', 'TELEN'),
            ('TELUK PANDAN', 'TELUK PANDAN'),
        )
        pilihankelurahan = (
            ('', ''),
            ('BATU TIMBAU', 'BATU TIMBAU'),
            ('BATU TIMBAU ULU', 'BATU TIMBAU ULU'),
            ('BENO HARAPAN', 'BENO HARAPAN'),
            ('HIMBA LESTARI', 'HIMBA LESTARI'),
            ('MAWAI INDAH', 'MAWAI INDAH'),
            ('MUGI RAHAYU', 'MUGI RAHAYU'),
            ('TELAGA', 'TELAGA'),
            ('KERAITAN', 'KERAITAN'),
            ('MUARA BENGALON', 'MUARA BENGALON'),
            ('SEKERAT', 'SEKERAT'),
            ('SEPASO', 'SEPASO'),
            ('SEPASO BARAT', 'SEPASO BARAT'),
            ('SEPASO SELATAN', 'SEPASO SELATAN'),
            ('SEPASO TIMUR', 'SEPASO TIMUR'),
            ('TEBANGAN LEBAK', 'TEBANGAN LEBAK'),
            ('TEPIAN BARU', 'TEPIAN BARU'),
            ('TEPIAN INDAH', 'TEPIAN INDAH'),
            ('TEPIAN LANGSAT', 'TEPIAN LANGSAT'),
            ('LONG BETUQ', 'LONG BETUQ'),
            ('LONG LEES', 'LONG LEES'),
            ('LONG NYELONG', 'LONG NYELONG'),
            ('LONG PEJENG', 'LONG PEJENG'),
            ('MEKAR BARU', 'MEKAR BARU'),
            ('MENDOM', 'MENDOM'),
            ('RANTAU SENTOSA', 'RANTAU SENTOSA'),
            ('BANGUN JAYA', 'BANGUN JAYA'),
            ('BUMI SEJAHTERA', 'BUMI SEJAHTERA'),
            ('CITRA MANUNGGAL JAYA', 'CITRA MANUNGGAL JAYA'),
            ('KALIORANG', 'KALIORANG'),
            ('SELANGKAU', 'SELANGKAU'),
            ("BA'AY", "BA'AY"),
            ('BATU LEPOQ', 'BATU LEPOQ'),
            ('KARANGAN DALAM', 'KARANGAN DALAM'),
            ('KARANGAN HILIR', 'KARANGAN HILIR'),
            ('KARANGAN SEBERANG', 'KARANGAN SEBERANG'),
            ('MUKTI LESTARI', 'MUKTI LESTARI'),
            ('PENGADAN', 'PENGADAN'),
            ('BUKIT PERMATA', 'BUKIT PERMATA'),
            ('BUMI ETAM', 'BUMI ETAM'),
            ('BUMI JAYA', 'BUMI JAYA'),
            ('BUMI RAPAK', 'BUMI RAPAK'),
            ('CIPTA GRAHA', 'CIPTA GRAHA'),
            ('KADUNGAN JAYA', 'KADUNGAN JAYA'),
            ('MATA AIR', 'MATA AIR'),
            ('PENGADAN BARU', 'PENGADAN BARU'),
            ('KOMBENG INDAH', 'KOMBENG INDAH'),
            ('MAKMUR JAYA', 'MAKMUR JAYA'),
            ('MARGA MULYA', 'MARGA MULYA'),
            ('MIAU BARU', 'MIAU BARU'),
            ('SRI PANTUN', 'SRI PANTUN'),
            ('SUKAMAJU', 'SUKAMAJU'),
            ('MELAN', 'MELAN'),
            ('MUKTI UTAMA', 'MUKTI UTAMA'),
            ('SEGOI MAKMUR', 'SEGOI MAKMUR'),
            ('SIKA MAKMUR', 'SIKA MAKMUR'),
            ('TANAH ABANG', 'TANAH ABANG'),
            ('GEMAR BARU', 'GEMAR BARU'),
            ('KELINJAU ILIR', 'KELINJAU ILIR'),
            ('KELINJAU ULU', 'KELINJAU ULU'),
            ('LONG NAH', 'LONG NAH'),
            ('LONG POQ BARU', 'LONG POQ BARU'),
            ('LONG TESAK', 'LONG TESAK'),
            ('MUARA DUN', 'MUARA DUN'),
            ('SENYIUR', 'SENYIUR'),
            ('TELUK BARU', 'TELUK BARU'),
            ('BATU BALAI', 'BATU BALAI'),
            ('MUARA BENGKAL ILIR', 'MUARA BENGKAL ILIR'),
            ('MUARA BENGKAL ULU', 'MUARA BENGKAL ULU'),
            ('MULUPAN', 'MULUPAN'),
            ('NGAYAU', 'NGAYAU'),
            ('SENAMBAH', 'SENAMBAH'),
            ('BENHES', 'BENHES'),
            ('DABEQ', 'DABEQ'),
            ('DIAQ LAY', 'DIAQ LAY'),
            ('JUK LUAY', 'JUK LUAY'),
            ('KARYA BHAKTI', 'KARYA BHAKTI'),
            ('LONG WEHEA', 'LONG WEHEA'),
            ('MUARA WAHAU', 'MUARA WAHAU'),
            ('NEHES LIAH BING', 'NEHES LIAH BING'),
            ('WAHAU BARU', 'WAHAU BARU'),
            ('WANASARI', 'WANASARI'),
            ('KEBON AGUNG', 'KEBON AGUNG'),
            ('MASALAP RAYA', 'MASALAP RAYA'),
            ('MUKTI JAYA', 'MUKTI JAYA'),
            ('PULUNG SARI', 'PULUNG SARI'),
            ('RANTAU MAKMUR', 'RANTAU MAKMUR'),
            ('TANJUNG LABU', 'TANJUNG LABU'),
            ('TEPIAN MAKMUR', 'TEPIAN MAKMUR'),
            ('MANUBAR', 'MANUBAR'),
            ('MANUBAR DALAM', 'MANUBAR DALAM'),
            ('MARUKANGAN', 'MARUKANGAN'),
            ('SANDARAN', 'SANDARAN'),
            ('SUSUK DALAM', 'SUSUK DALAM'),
            ('SUSUK LUAR', 'SUSUK LUAR'),
            ('SUSUK TENGAH', 'SUSUK TENGAH'),
            ('TADOAN', 'TADOAN'),
            ('TANJUNG MANGKALIHAT', 'TANJUNG MANGKALIHAT'),
            ('SANGATTA SELATAN', 'SANGATTA SELATAN'),
            ('SANGKIMA', 'SANGKIMA'),
            ('SANGKIMA LAMA', 'SANGKIMA LAMA'),
            ('SINGA GEWEH', 'SINGA GEWEH'),
            ('SANGATTA UTARA', 'SANGATTA UTARA'),
            ('SINGA GEMBARA', 'SINGA GEMBARA'),
            ('SWARGA BARA', 'SWARGA BARA'),
            ('TELUK LINGGA', 'TELUK LINGGA'),
            ('PINANG RAYA', 'PINANG RAYA'),
            ('BENUA BARU ILIR', 'BENUA BARU ILIR'),
            ('BENUA BARU ULU', 'BENUA BARU ULU'),
            ('KERAYAAN', 'KERAYAAN'),
            ('KOLEK', 'KOLEK'),
            ('MALOY', 'MALOY'),
            ('MANDAU PANTAI SEJAHTERA', 'MANDAU PANTAI SEJAHTERA'),
            ('MANDU DALAM', 'MANDU DALAM'),
            ('PELAWAN', 'PELAWAN'),
            ('PERIDAN', 'PERIDAN'),
            ('PERUPUK', 'PERUPUK'),
            ('PULAU MIANG', 'PULAU MIANG'),
            ('SAQA', 'SAQA'),
            ('SEMPAYAU', 'SEMPAYAU'),
            ('TANJUNG MANIS', 'TANJUNG MANIS'),
            ('TEPIAN TARAP', 'TEPIAN TARAP'),
            ('JUK AYAQ', 'JUK AYAQ'),
            ('KERNYANYAN', 'KERNYANYAN'),
            ('LONG MELAH', 'LONG MELAH'),
            ('LONG NORAN', 'LONG NORAN'),
            ('LONG SEGAR', 'LONG SEGAR'),
            ('MARAH HALOQ', 'MARAH HALOQ'),
            ('MUARA PANTUN', 'MUARA PANTUN'),
            ('DANAU REDAN', 'DANAU REDAN'),
            ('KANDOLO', 'KANDOLO'),
            ('MARTADINATA', 'MARTADINATA'),
            ('SUKA RAHMAT', 'SUKA RAHMAT'),
            ('TELUK PANDAN', 'TELUK PANDAN'),
        )
        widgets = {
            # 'judul': forms.TextInput({'class': 'form-control'}),
            # 'penulis': forms.TextInput({'class': 'form-control'}),
            # 'penerbit': forms.TextInput({'class': 'form-control'}),
            # 'jumlah': forms.NumberInput({'class': 'form-control'}),
            # 'kelompok_id': forms.Select({'class': 'form-control'}),
            'nama_dpt': forms.TextInput({'class': 'form-control'}),
            'kota': forms.Select({'class': 'form-control'}, choices=pilihankota),
            'kecamatan': forms.Select({'class': 'form-control'}, choices=pilihankecamatan),
            'kelurahan': forms.Select({'class': 'form-control'}, choices=pilihankelurahan),
            'alamat': forms.TextInput({'class': 'form-control'}),
            'nik': forms.NumberInput({'class': 'form-control'}),
            'nomor_hp': forms.NumberInput({'class': 'form-control'}),
            'nomor_rekening': forms.NumberInput({'class': 'form-control'}),
            'nomor_kk': forms.NumberInput({'class': 'form-control'}),
            'tanggal_lahir': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_input_data': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_honor': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_telespocheck': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'rt': forms.NumberInput({'class': 'form-control'}),
            'nominal_honor': forms.NumberInput({'class': 'form-control'}),
            'bank': forms.TextInput({'class': 'form-control'}),
            'status_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan_telespocheck': forms.TextInput({'class': 'form-control'}),
            'telespochecker': forms.Select({'class': 'form-control'}),
            'hasil_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan': forms.TextInput({'class': 'form-control'}),
            'nama_pemilik_rekening': forms.TextInput({'class': 'form-control'}),
            'inputer': forms.Select({'class': 'form-control'}),
            'keterangan_honor': forms.TextInput({'class': 'form-control'}),
        }
