from django.forms import ModelForm
from django import forms
from kubar.models import Kubar


class FormKubar(ModelForm):
    class Meta:
        model = Kubar
        fields = '__all__'
        pilihankota = (
            ('KUTAI BARAT', 'KUTAI BARAT'),
        )
        pilihankecamatan = (
            ('', ''),
            ('BARONG TONGKOK', 'BARONG TONGKOK'),
            ('BENTIAN BESAR', 'BENTIAN BESAR'),
            ('BONGAN', 'BONGAN'),
            ('DAMAI', 'DAMAI'),
            ('JEMPANG', 'JEMPANG'),
            ('LINGGANG BIGUNG', 'LINGGANG BIGUNG'),
            ('LONG IRAM', 'LONG IRAM'),
            ('MELAK', 'MELAK'),
            ('MOOK MANAAR BULATN', 'MOOK MANAAR BULATN'),
            ('MUARA LAWA', 'MUARA LAWA'),
            ('MUARA PAHU', 'MUARA PAHU'),
            ('NYUATAN', 'NYUATAN'),
            ('PENYINGGAHAN', 'PENYINGGAHAN'),
            ('SEKOLAQ DARAT', 'SEKOLAQ DARAT'),
            ('SILUQ NGURAI', 'SILUQ NGURAI'),
            ('TERING', 'TERING'),
        )
        pilihankelurahan = (
            ('', ''),
            ('ASA', 'ASA'),
            ('BALOK ASA', 'BALOK ASA'),
            ('BARONG TONGKOK', 'BARONG TONGKOK'),
            ('BELEMPUNG ULAQ', 'BELEMPUNG ULAQ'),
            ('ENGKUNI PASEK', 'ENGKUNI PASEK'),
            ('GELEO ASA', 'GELEO ASA'),
            ('GELEO BARU', 'GELEO BARU'),
            ('GEMUHAN ASA', 'GEMUHAN ASA'),
            ('JUAQ ASA', 'JUAQ ASA'),
            ('JUHAN ASA', 'JUHAN ASA'),
            ('MENCIMIN', 'MENCIMIN'),
            ('MUARA ASA', 'MUARA ASA'),
            ('NGENYAN ASA', 'NGENYAN ASA'),
            ('OMBAU ASA', 'OMBAU ASA'),
            ('ONGKO ASA', 'ONGKO ASA'),
            ('PEPAS EHENG', 'PEPAS EHENG'),
            ('PEPES ASA', 'PEPES ASA'),
            ('REJO BASUKI', 'REJO BASUKI'),
            ('SENDAWAR', 'SENDAWAR'),
            ('SIMPANG RAYA', 'SIMPANG RAYA'),
            ('ANAN JAYA', 'ANAN JAYA'),
            ('DILANG PUTI', 'DILANG PUTI'),
            ('JELMU SIBAK', 'JELMU SIBAK'),
            ('PENARUNG', 'PENARUNG'),
            ('RANDA EMPAS', 'RANDA EMPAS'),
            ('SAMBUNG', 'SAMBUNG'),
            ('SUAKONG', 'SUAKONG'),
            ('TENDE', 'TENDE'),
            ('TUKUQ', 'TUKUQ'),
            ('BUKIT HARAPAN', 'BUKIT HARAPAN'),
            ('DERAYA', 'DERAYA'),
            ('GERUNGUNG', 'GERUNGUNG'),
            ('JAMBUK', 'JAMBUK'),
            ('JAMBUK MAKMUR', 'JAMBUK MAKMUR'),
            ('LEMPER', 'LEMPER'),
            ('MUARA GUSIK', 'MUARA GUSIK'),
            ('MUARA KEDANG', 'MUARA KEDANG'),
            ('MUARA SIRAM', 'MUARA SIRAM'),
            ('PENAWAI', 'PENAWAI'),
            ('PERENG TALIQ', 'PERENG TALIQ'),
            ('RESAK', 'RESAK'),
            ('SIRAM JAYA', 'SIRAM JAYA'),
            ('SIRAM MAKMUR', 'SIRAM MAKMUR'),
            ('TANJUNG SARI', 'TANJUNG SARI'),
            ('TANUNG SOKE', 'TANUNG SOKE'),
            ('BENUNG', 'BENUNG'),
            ('BERMAI', 'BERMAI'),
            ('BESIQ', 'BESIQ'),
            ('DAMAI KOTA', 'DAMAI KOTA'),
            ('DAMAI SEBERANG', 'DAMAI SEBERANG'),
            ('JENGAN DANUM', 'JENGAN DANUM'),
            ('KEAY', 'KEAY'),
            ('KELIAN', 'KELIAN'),
            ('LUMPAT DAHUQ', 'LUMPAT DAHUQ'),
            ('MANTAR', 'MANTAR'),
            ('MENDIKA', 'MENDIKA'),
            ('MUARA BOMBOY', 'MUARA BOMBOY'),
            ('MUARA NILIQ', 'MUARA NILIQ'),
            ('MUARA NYAHING', 'MUARA NYAHING'),
            ('MUARA TOKONG', 'MUARA TOKONG'),
            ('SEMPATN', 'SEMPATN'),
            ('TAPULANG', 'TAPULANG'),
            ('BEKOKONG MAKMUR', 'BEKOKONG MAKMUR'),
            ('LEMBONAH', 'LEMBONAH'),
            ('MANCONG', 'MANCONG'),
            ('MUARA NAYAN', 'MUARA NAYAN'),
            ('MUARA OHONG', 'MUARA OHONG'),
            ('MUARA TAE', 'MUARA TAE'),
            ('PENTAT', 'PENTAT'),
            ('PERIGIQ', 'PERIGIQ'),
            ('PULAU LANTING', 'PULAU LANTING'),
            ('TANJUNG ISUY', 'TANJUNG ISUY'),
            ('TANJUNG JAN', 'TANJUNG JAN'),
            ('TANJUNG JONE', 'TANJUNG JONE'),
            ('BANGUN SARI', 'BANGUN SARI'),
            ('BIGUNG BARU', 'BIGUNG BARU'),
            ('LINGGANG AMER', 'LINGGANG AMER'),
            ('LINGGANG BIGUNG', 'LINGGANG BIGUNG'),
            ('LINGGANG KEBUT', 'LINGGANG KEBUT'),
            ('LINGGANG MAPAN', 'LINGGANG MAPAN'),
            ('LINGGANG MELAPEH', 'LINGGANG MELAPEH'),
            ('LINGGANG MENCELEW', 'LINGGANG MENCELEW'),
            ('MELAPEH BARU', 'MELAPEH BARU'),
            ('PURWODADI', 'PURWODADI'),
            ('TUTUNG', 'TUTUNG'),
            ('ANAH', 'ANAH'),
            ('KELIAN LUAR', 'KELIAN LUAR'),
            ('KELIWAI', 'KELIWAI'),
            ('LONG DALIQ', 'LONG DALIQ'),
            ('LONG IRAM BAYAN', 'LONG IRAM BAYAN'),
            ('LONG IRAM ILIR', 'LONG IRAM ILIR'),
            ('LONG IRAM KOTA', 'LONG IRAM KOTA'),
            ('LONG IRAM SEBERANG', 'LONG IRAM SEBERANG'),
            ('MUARA LEBAN', 'MUARA LEBAN'),
            ('SUKOMULYO', 'SUKOMULYO'),
            ('UJOH HALANG', 'UJOH HALANG'),
            ('EMPAKUQ', 'EMPAKUQ'),
            ('EMPAS', 'EMPAS'),
            ('MELAK ILIR', 'MELAK ILIR'),
            ('MELAK ULU', 'MELAK ULU'),
            ('MUARA BENANGAQ', 'MUARA BENANGAQ'),
            ('MUARA BUNYUT', 'MUARA BUNYUT'),
            ('ABIT', 'ABIT'),
            ('GADUR', 'GADUR'),
            ('GEMURUH', 'GEMURUH'),
            ('GUNUNG RAMPAH', 'GUNUNG RAMPAH'),
            ('JENGAN', 'JENGAN'),
            ('KELUMPANG', 'KELUMPANG'),
            ('LINGGANG MARIMUN', 'LINGGANG MARIMUN'),
            ('MERAYAQ', 'MERAYAQ'),
            ('MUARA BATUQ', 'MUARA BATUQ'),
            ('MUARA JAWAQ', 'MUARA JAWAQ'),
            ('MUARA KALAQ', 'MUARA KALAQ'),
            ('REMBAYAN', 'REMBAYAN'),
            ('SAKAQ LOTOQ', 'SAKAQ LOTOQ'),
            ('SAKAQ TADA', 'SAKAQ TADA'),
            ('TONDOH', 'TONDOH'),
            ('BENGGERIS', 'BENGGERIS'),
            ('CEMPEDES', 'CEMPEDES'),
            ('DINGIN', 'DINGIN'),
            ('LAMBING', 'LAMBING'),
            ('LOTAQ', 'LOTAQ'),
            ('MUARA BEGAI', 'MUARA BEGAI'),
            ('MUARA LAWA', 'MUARA LAWA'),
            ('PAYANG', 'PAYANG'),
            ('DASAQ', 'DASAQ'),
            ('GUNUNG BAYAN', 'GUNUNG BAYAN'),
            ('JERANG DAYAK', 'JERANG DAYAK'),
            ('JERANG MELAYU', 'JERANG MELAYU'),
            ('MENDUNG', 'MENDUNG'),
            ('MUARA BAROH', 'MUARA BAROH'),
            ('MUARA BELOAN', 'MUARA BELOAN'),
            ('SEBELANG', 'SEBELANG'),
            ('TANJUNG LAONG', 'TANJUNG LAONG'),
            ('TANJUNG PAGAR', 'TANJUNG PAGAR'),
            ('TELUK TEMPUDAU', 'TELUK TEMPUDAU'),
            ('TEPIAN ULAQ', 'TEPIAN ULAQ'),
            ('AWAI', 'AWAI'),
            ('DEMPAR', 'DEMPAR'),
            ('INTU LINGAU', 'INTU LINGAU'),
            ('JONTAI', 'JONTAI'),
            ('LAKAN BILEM', 'LAKAN BILEM'),
            ("MU'UT", "MU'UT"),
            ('SEMBUAN', 'SEMBUAN'),
            ('SENTALAR', 'SENTALAR'),
            ('TEMULA', 'TEMULA'),
            ('TERAJUK', 'TERAJUK'),
            ('BAKUNG', 'BAKUNG'),
            ('LOA DERAS', 'LOA DERAS'),
            ('MINTA', 'MINTA'),
            ('PENYINGGAHAN ILIR', 'PENYINGGAHAN ILIR'),
            ('PENYINGGAHAN ULU', 'PENYINGGAHAN ULU'),
            ('TANJUNG HAUR', 'TANJUNG HAUR'),
            ('LELENG', 'LELENG'),
            ('SEKOLAQ DARAT', 'SEKOLAQ DARAT'),
            ('SEKOLAQ JOLEQ', 'SEKOLAQ JOLEQ'),
            ('SEKOLAQ MULIAQ', 'SEKOLAQ MULIAQ'),
            ('SEKOLAQ ODAY', 'SEKOLAQ ODAY'),
            ('SRIMULYO', 'SRIMULYO'),
            ('SUMBER BANGUN', 'SUMBER BANGUN'),
            ('BENTAS', 'BENTAS'),
            ('BETUNG', 'BETUNG'),
            ('KALIQ', 'KALIQ'),
            ('KENDISIQ', 'KENDISIQ'),
            ('KENYANYAN', 'KENYANYAN'),
            ('KIAQ', 'KIAQ'),
            ('LENDIAN LIANG NAYUQ', 'LENDIAN LIANG NAYUQ'),
            ('MUARA KELAWIT', 'MUARA KELAWIT'),
            ('MUARA PONAQ', 'MUARA PONAQ'),
            ('MUHUR', 'MUHUR'),
            ('PENAWANG', 'PENAWANG'),
            ('RIKONG', 'RIKONG'),
            ('SANG-SANG', 'SANG-SANG'),
            ('TANAH MEA', 'TANAH MEA'),
            ('TEBISAQ', 'TEBISAQ'),
            ('TENDIQ', 'TENDIQ'),
            ('BANJAREJO', 'BANJAREJO'),
            ('GABUNG BARU', 'GABUNG BARU'),
            ('JELEMUQ', 'JELEMUQ'),
            ('KELIAN DALAM', 'KELIAN DALAM'),
            ('KELUBAQ', 'KELUBAQ'),
            ('MUARA MUJAN', 'MUARA MUJAN'),
            ('MUYUB AKET', 'MUYUB AKET'),
            ('MUYUB ILIR', 'MUYUB ILIR'),
            ('MUYUB ULU', 'MUYUB ULU'),
            ('PURWOREJO', 'PURWOREJO'),
            ('TERING BARU', 'TERING BARU'),
            ('TERING LAMA', 'TERING LAMA'),
            ('TERING LAMA ULU', 'TERING LAMA ULU'),
            ('TERING SEBERANG', 'TERING SEBERANG'),
            ('TUKUL', 'TUKUL'),
        )
        widgets = {
            # 'judul': forms.TextInput({'class': 'form-control'}),
            # 'penulis': forms.TextInput({'class': 'form-control'}),
            # 'penerbit': forms.TextInput({'class': 'form-control'}),
            # 'jumlah': forms.NumberInput({'class': 'form-control'}),
            # 'kelompok_id': forms.Select({'class': 'form-control'}),
            'nama_dpt': forms.TextInput({'class': 'form-control'}),
            'kota': forms.Select({'class': 'form-control'}, choices=pilihankota),
            'kecamatan': forms.Select({'class': 'form-control'}, choices=pilihankecamatan),
            'kelurahan': forms.Select({'class': 'form-control'}, choices=pilihankelurahan),
            'alamat': forms.TextInput({'class': 'form-control'}),
            'nik': forms.NumberInput({'class': 'form-control'}),
            'nomor_hp': forms.NumberInput({'class': 'form-control'}),
            'nomor_rekening': forms.NumberInput({'class': 'form-control'}),
            'nomor_kk': forms.NumberInput({'class': 'form-control'}),
            'tanggal_lahir': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_input_data': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_honor': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_telespocheck': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'rt': forms.NumberInput({'class': 'form-control'}),
            'nominal_honor': forms.NumberInput({'class': 'form-control'}),
            'bank': forms.TextInput({'class': 'form-control'}),
            'status_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan_telespocheck': forms.TextInput({'class': 'form-control'}),
            'telespochecker': forms.Select({'class': 'form-control'}),
            'hasil_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan': forms.TextInput({'class': 'form-control'}),
            'nama_pemilik_rekening': forms.TextInput({'class': 'form-control'}),
            'inputer': forms.Select({'class': 'form-control'}),
            'keterangan_honor': forms.TextInput({'class': 'form-control'}),
        }
