# Generated by Django 4.0.1 on 2022-02-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='alamat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='keterangan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='nama_pemilik_rekening',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='nik',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='nominal_honor',
            field=models.IntegerField(default='Rp.'),
        ),
        migrations.AlterField(
            model_name='database',
            name='nomor_hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='nomor_kk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='nomor_rekening',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='rt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='tanggal_honor',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
