# Generated by Django 4.0.1 on 2022-02-19 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harum', '0002_alter_database_alamat_alter_database_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='hasil_telespocheck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harum.hasil_telespocheck'),
        ),
        migrations.AlterField(
            model_name='database',
            name='inputer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harum.inputer'),
        ),
        migrations.AlterField(
            model_name='database',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harum.kecamatan'),
        ),
        migrations.AlterField(
            model_name='database',
            name='kelurahan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harum.kelurahan'),
        ),
        migrations.AlterField(
            model_name='database',
            name='keterangan_honor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='keterangan_telespocheck',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='kota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harum.kota'),
        ),
        migrations.AlterField(
            model_name='database',
            name='nominal_honor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='status_telespocheck_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harum.status_telespocheck'),
        ),
        migrations.AlterField(
            model_name='database',
            name='tanggal_input_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='tanggal_telespocheck',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='telespochecker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harum.telespochecker'),
        ),
    ]
