# Generated by Django 4.0.1 on 2022-02-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harum', '0003_alter_database_hasil_telespocheck_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='status_telespocheck_id',
            new_name='status_telespocheck',
        ),
    ]
