from django.forms import ModelForm
from django import forms
from kukar.models import Kukar


class FormKukar(ModelForm):
    class Meta:
        model = Kukar
        fields = '__all__'
        pilihankota = (
            ('KUKAR', 'KUKAR'),
        )
        pilihankecamatan = (
            ('', ''),
            ('ANGGANA', 'ANGGANA'),
            ('KEMBANG JANGGUT', 'KEMBANG JANGGUT'),
            ('KENOHAN', 'KENOHAN'),
            ('KOTA BANGUN', 'KOTA BANGUN'),
            ('LOA JANAN', 'LOA JANAN'),
            ('LOA KULU', 'LOA KULU'),
            ('MARANG KAYU', 'MARANG KAYU'),
            ('MUARA BADAK', 'MUARA BADAK'),
            ('MUARA JAWA', 'MUARA JAWA'),
            ('MUARA KAMAN', 'MUARA KAMAN'),
            ('MUARA MUNTAI', 'MUARA MUNTAI'),
            ('MUARA WIS', 'MUARA WIS'),
            ('SAMBOJA', 'SAMBOJA'),
            ('SANGA SANGA', 'SANGA SANGA'),
            ('SEBULU', 'SEBULU'),
            ('TABANG', 'TABANG'),
            ('TENGGARONG', 'TENGGARONG'),
            ('TENGGARONG SEBERANG', 'TENGGARONG SEBERANG'),
        )
        pilihankelurahan = (
            ('', ''),
            ('ANGGANA', 'ANGGANA'),
            ('HANDIL TERUSAN', 'HANDIL TERUSAN'),
            ('KUTAI LAMA', 'KUTAI LAMA'),
            ('MUARA PANTUAN', 'MUARA PANTUAN'),
            ('SEPATIN', 'SEPATIN'),
            ('SUNGAI MERIAM', 'SUNGAI MERIAM'),
            ('TANI BARU', 'TANI BARU'),
            ('BUKIT LAYANG', 'BUKIT LAYANG'),
            ('GENTING TANAH', 'GENTING TANAH'),
            ('HAMBAU', 'HAMBAU'),
            ('KELEKAT', 'KELEKAT'),
            ('KEMBANG JANGGUT', 'KEMBANG JANGGUT'),
            ('LOA SAKOH', 'LOA SAKOH'),
            ('LONG BELEH HALOQ', 'LONG BELEH HALOQ'),
            ('LONG BELEH MODANG', 'LONG BELEH MODANG'),
            ('MUAI', 'MUAI'),
            ('PERDANA', 'PERDANA'),
            ('PULAU PINANG', 'PULAU PINANG'),
            ('KAHALA', 'KAHALA'),
            ('KAHALA ILIR', 'KAHALA ILIR'),
            ('LAMIN PULUT', 'LAMIN PULUT'),
            ('LAMIN TELIHAN', 'LAMIN TELIHAN'),
            ('SEMAYANG', 'SEMAYANG'),
            ('TELUK BINGKAI', 'TELUK BINGKAI'),
            ('TELUK MUDA', 'TELUK MUDA'),
            ('TUANA TUHA', 'TUANA TUHA'),
            ('TUBUHAN', 'TUBUHAN'),
            ('BENUA BARU', 'BENUA BARU'),
            ('KEDANG IPIL', 'KEDANG IPIL'),
            ('KEDANG MURUNG', 'KEDANG MURUNG'),
            ('KOTA BANGUN I', 'KOTA BANGUN I'),
            ('KOTA BANGUN II', 'KOTA BANGUN II'),
            ('KOTA BANGUN III', 'KOTA BANGUN III'),
            ('KOTA BANGUN ILIR', 'KOTA BANGUN ILIR'),
            ('KOTA BANGUN SEBERANG', 'KOTA BANGUN SEBERANG'),
            ('KOTA BANGUN ULU', 'KOTA BANGUN ULU'),
            ('LIANG', 'LIANG'),
            ('LIANG ULU', 'LIANG ULU'),
            ('LOLENG', 'LOLENG'),
            ('MUHURAN', 'MUHURAN'),
            ('PELA', 'PELA'),
            ('SANGKULIMAN', 'SANGKULIMAN'),
            ('SARI NADI', 'SARI NADI'),
            ('SEBELIMBINGAN', 'SEBELIMBINGAN'),
            ('SEDULANG', 'SEDULANG'),
            ('SUKA BUMI', 'SUKA BUMI'),
            ('SUMBER SARI', 'SUMBER SARI'),
            ('WONOSARI', 'WONOSARI'),
            ('BAKUNGAN', 'BAKUNGAN'),
            ('BATUAH', 'BATUAH'),
            ('LOA DURI ILIR', 'LOA DURI ILIR'),
            ('LOA DURI ULU', 'LOA DURI ULU'),
            ('LOA JANAN ULU', 'LOA JANAN ULU'),
            ('PURWAJAYA', 'PURWAJAYA'),
            ('TANI BHAKTI', 'TANI BHAKTI'),
            ('TANI HARAPAN', 'TANI HARAPAN'),
            ('JEMBAYAN', 'JEMBAYAN'),
            ('JEMBAYAN DALAM', 'JEMBAYAN DALAM'),
            ('JEMBAYAN TENGAH', 'JEMBAYAN TENGAH'),
            ('JONGGON', 'JONGGON'),
            ('JONGKANG', 'JONGKANG'),
            ('KARYA UTAMA', 'KARYA UTAMA'),
            ('LOA KULU KOTA', 'LOA KULU KOTA'),
            ('LOH SUMBER', 'LOH SUMBER'),
            ('LUNG ANAI', 'LUNG ANAI'),
            ('MARGA RAHAYU', 'MARGA RAHAYU'),
            ('PONORAGAN', 'PONORAGAN'),
            ('REMPANGA', 'REMPANGA'),
            ('SEPAKAT', 'SEPAKAT'),
            ('SUNGAI PAYANG', 'SUNGAI PAYANG'),
            ('MAKARTI', 'MAKARTI'),
            ('PERANGAT BARU', 'PERANGAT BARU'),
            ('PERANGAT SELATAN', 'PERANGAT SELATAN'),
            ('SAMBERA BARU', 'SAMBERA BARU'),
            ('SANTAN ULU', 'SANTAN ULU'),
            ('SANTAN ILIR', 'SANTAN ILIR'),
            ('SANTAN TENGAH', 'SANTAN TENGAH'),
            ('BUNGA PUTIH', 'BUNGA PUTIH'),
            ('KERSIK', 'KERSIK'),
            ('SEMANGKO', 'SEMANGKO'),
            ('SEBUNTAL', 'SEBUNTAL'),
            ('BADAK BARU', 'BADAK BARU'),
            ('BADAK MEKAR', 'BADAK MEKAR'),
            ('BATU BATU', 'BATU BATU'),
            ('GAS ALAM BADAK I', 'GAS ALAM BADAK I'),
            ('MUARA BADAK ILIR', 'MUARA BADAK ILIR'),
            ('MUARA BADAK ULU', 'MUARA BADAK ULU'),
            ('SALIKI', 'SALIKI'),
            ('SALO CELLA', 'SALO CELLA'),
            ('SALO PALAI', 'SALO PALAI'),
            ('SUKA DAMAI', 'SUKA DAMAI'),
            ('SUNGAI BAWANG', 'SUNGAI BAWANG'),
            ('TANAH DATAR', 'TANAH DATAR'),
            ('TANJUNG LIMAU', 'TANJUNG LIMAU'),
            ('DONDANG', 'DONDANG'),
            ('MUARA JAWA ILIR', 'MUARA JAWA ILIR'),
            ('MUARA JAWA PESISIR', 'MUARA JAWA PESISIR'),
            ('MUARA JAWA TENGAH', 'MUARA JAWA TENGAH'),
            ('MUARA JAWA ULU', 'MUARA JAWA ULU'),
            ('MUARA KEMBANG', 'MUARA KEMBANG'),
            ('TAMA POLE', 'TAMA POLE'),
            ('TELUK DALAM', 'TELUK DALAM'),
        )
        widgets = {
            # 'judul': forms.TextInput({'class': 'form-control'}),
            # 'penulis': forms.TextInput({'class': 'form-control'}),
            # 'penerbit': forms.TextInput({'class': 'form-control'}),
            # 'jumlah': forms.NumberInput({'class': 'form-control'}),
            # 'kelompok_id': forms.Select({'class': 'form-control'}),
            'nama_dpt': forms.TextInput({'class': 'form-control'}),
            'kota': forms.Select({'class': 'form-control'}, choices=pilihankota),
            'kecamatan': forms.Select({'class': 'form-control'}, choices=pilihankecamatan),
            'kelurahan': forms.Select({'class': 'form-control'}, choices=pilihankelurahan),
            'alamat': forms.TextInput({'class': 'form-control'}),
            'nik': forms.NumberInput({'class': 'form-control'}),
            'nomor_hp': forms.NumberInput({'class': 'form-control'}),
            'nomor_rekening': forms.NumberInput({'class': 'form-control'}),
            'nomor_kk': forms.NumberInput({'class': 'form-control'}),
            'tanggal_lahir': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_input_data': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_honor': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_telespocheck': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'rt': forms.NumberInput({'class': 'form-control'}),
            'nominal_honor': forms.NumberInput({'class': 'form-control'}),
            'bank': forms.TextInput({'class': 'form-control'}),
            'status_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan_telespocheck': forms.TextInput({'class': 'form-control'}),
            'telespochecker': forms.Select({'class': 'form-control'}),
            'hasil_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan': forms.TextInput({'class': 'form-control'}),
            'nama_pemilik_rekening': forms.TextInput({'class': 'form-control'}),
            'inputer': forms.Select({'class': 'form-control'}),
            'keterangan_honor': forms.TextInput({'class': 'form-control'}),
        }
