from django.forms import ModelForm
from django import forms
from samarinda.models import Samarinda


class FormSamarinda(ModelForm):
    class Meta:
        model = Samarinda
        fields = '__all__'
        pilihankota = (
            ('SAMARINDA', 'SAMARINDA'),
        )
        pilihankecamatan = (
            ('', ''),
            ('LOA JANAN ILIR', 'LOA JANAN ILIR'),
            ('PALARAN', 'PALARAN'),
            ('SAMARINDA ILIR', 'SAMARINDA ILIR'),
            ('SAMARINDA KOTA', 'SAMARINDA KOTA'),
            ('SAMARINDA SEBERANG', 'SAMARINDA SEBERANG'),
            ('SAMARINDA ULU', 'SAMARINDA ULU'),
            ('SAMARINDA UTARA', 'SAMARINDA UTARA'),
            ('SAMBUTAN', 'SAMBUTAN'),
            ('SUNGAI KUNJANG', 'SUNGAI KUNJANG'),
            ('SUNGAI PINANG', 'SUNGAI PINANG'),
        )
        pilihankelurahan = (
            ('', ''),
            ('HARAPAN BARU', 'HARAPAN BARU'),
            ('RAPAK DALAM', 'RAPAK DALAM'),
            ('SENGKOTEK', 'SENGKOTEK'),
            ('SIMPANG TIGA', 'SIMPANG TIGA'),
            ('TANI AMAN', 'TANI AMAN'),
            ('BANTUAS', 'BANTUAS'),
            ('BUKUAN', 'BUKUAN'),
            ('HANDIL BAKTI', 'HANDIL BAKTI'),
            ('RAWA MAKMUR', 'RAWA MAKMUR'),
            ('SIMPANG PASIR', 'SIMPANG PASIR'),
            ('PELITA', 'PELITA'),
            ('SELILI', 'SELILI'),
            ('SIDODAMAI', 'SIDODAMAI'),
            ('SIDOMULYO', 'SIDOMULYO'),
            ('SUNGAI DAMA', 'SUNGAI DAMA'),
            ('BUGIS', 'BUGIS'),
            ('KARANG MUMUS', 'KARANG MUMUS'),
            ('PASAR PAGI', 'PASAR PAGI'),
            ('PELABUHAN', 'PELABUHAN'),
            ('SUNGAI PINANG LUAR', 'SUNGAI PINANG LUAR'),
            ('BAQA', 'BAQA'),
            ('GUNUNG PANJANG', 'GUNUNG PANJANG'),
            ('MANGKUPALAS', 'MANGKUPALAS'),
            ('MESJID', 'MESJID'),
            ('SUNGAI KELEDANG', 'SUNGAI KELEDANG'),
            ('TENUN SAMARINDA', 'TENUN SAMARINDA'),
            ('AIR HITAM', 'AIR HITAM'),
            ('AIR PUTIH', 'AIR PUTIH'),
            ('BUKIT PINANG', 'BUKIT PINANG'),
            ('DADI MULYA', 'DADI MULYA'),
            ('GUNUNG KELUA', 'GUNUNG KELUA'),
            ('JAWA', 'JAWA'),
            ('SIDODADI', 'SIDODADI'),
            ('TELUK LERONG ILIR', 'TELUK LERONG ILIR'),
            ('BUDAYA PAMPANG', 'BUDAYA PAMPANG'),
            ('LEMPAKE', 'LEMPAKE'),
            ('SEMPAJA BARAT', 'SEMPAJA BARAT'),
            ('SEMPAJA SELATAN', 'SEMPAJA SELATAN'),
            ('SEMPAJA TIMUR', 'SEMPAJA TIMUR'),
            ('SEMPAJA UTARA', 'SEMPAJA UTARA'),
            ('SUNGAI SIRING', 'SUNGAI SIRING'),
            ('TANAH MERAH', 'TANAH MERAH'),
            ('MAKROMAN', 'MAKROMAN'),
            ('PULAU ATAS', 'PULAU ATAS'),
            ('SAMBUTAN', 'SAMBUTAN'),
            ('SINDANG SARI', 'SINDANG SARI'),
            ('SUNGAI KAPIH', 'SUNGAI KAPIH'),
            ('KARANG ANYAR', 'KARANG ANYAR'),
            ('KARANG ASAM ILIR', 'KARANG ASAM ILIR'),
            ('KARANG ASAM ULU', 'KARANG ASAM ULU'),
            ('LOA BAKUNG', 'LOA BAKUNG'),
            ('LOA BUAH', 'LOA BUAH'),
            ('LOK BAHU', 'LOK BAHU'),
            ('TELUK LERONG ULU', 'TELUK LERONG ULU'),
            ('BANDARA', 'BANDARA'),
            ('GUNUNG LINGAI', 'GUNUNG LINGAI'),
            ('MUGIREJO', 'MUGIREJO'),
            ('SUNGAI PINANG DALAM', 'SUNGAI PINANG DALAM'),
            ('TEMINDUNG PERMAI', 'TEMINDUNG PERMAI'),
        )
        widgets = {
            # 'judul': forms.TextInput({'class': 'form-control'}),
            # 'penulis': forms.TextInput({'class': 'form-control'}),
            # 'penerbit': forms.TextInput({'class': 'form-control'}),
            # 'jumlah': forms.NumberInput({'class': 'form-control'}),
            # 'kelompok_id': forms.Select({'class': 'form-control'}),
            'nama_dpt': forms.TextInput({'class': 'form-control'}),
            'kota': forms.Select({'class': 'form-control'}, choices=pilihankota),
            'kecamatan': forms.Select({'class': 'form-control'}, choices=pilihankecamatan),
            'kelurahan': forms.Select({'class': 'form-control'}, choices=pilihankelurahan),
            'alamat': forms.TextInput({'class': 'form-control'}),
            'nik': forms.NumberInput({'class': 'form-control'}),
            'nomor_hp': forms.NumberInput({'class': 'form-control'}),
            'nomor_rekening': forms.NumberInput({'class': 'form-control'}),
            'nomor_kk': forms.NumberInput({'class': 'form-control'}),
            'tanggal_lahir': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_input_data': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_honor': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_telespocheck': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'rt': forms.NumberInput({'class': 'form-control'}),
            'nominal_honor': forms.NumberInput({'class': 'form-control'}),
            'bank': forms.TextInput({'class': 'form-control'}),
            'status_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan_telespocheck': forms.TextInput({'class': 'form-control'}),
            'telespochecker': forms.Select({'class': 'form-control'}),
            'hasil_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan': forms.TextInput({'class': 'form-control'}),
            'nama_pemilik_rekening': forms.TextInput({'class': 'form-control'}),
            'inputer': forms.Select({'class': 'form-control'}),
            'keterangan_honor': forms.TextInput({'class': 'form-control'}),
        }
