from django.forms import ModelForm
from django import forms
from paser.models import Paser


class FormPaser(ModelForm):
    class Meta:
        model = Paser
        fields = '__all__'
        pilihankota = (
            ('PASER', 'PASER'),
        )
        pilihankecamatan = (
            ('', ''),
            ('BATU ENGAU', 'BATU ENGAU'),
            ('BATU SOPANG', 'BATU SOPANG'),
            ('KUARO', 'KUARO'),
            ('LONG IKIS', 'LONG IKIS'),
            ('LONG KALI', 'LONG KALI'),
            ('MUARA KOMAM', 'MUARA KOMAM'),
            ('MUARA SAMU', 'MUARA SAMU'),
            ('PASIR BALENGKONG', 'PASIR BALENGKONG'),
            ('TANAH GROGOT', 'TANAH GROGOT'),
            ('TANJUNG HARAPAN', 'TANJUNG HARAPAN'),
        )
        pilihankelurahan = (
            ('', ''),
            ('BAI JAYA', 'BAI JAYA'),
            ('KERANG', 'KERANG'),
            ('KERANG DAYO', 'KERANG DAYO'),
            ('LANGGAI', 'LANGGAI'),
            ('LOMU', 'LOMU'),
            ('MENGKUDU', 'MENGKUDU'),
            ('PENGGUREN JAYA', 'PENGGUREN JAYA'),
            ('PETANGIS', 'PETANGIS'),
            ('RIWANG', 'RIWANG'),
            ('SAING PRUPUK', 'SAING PRUPUK'),
            ('SEGENDANG', 'SEGENDANG'),
            ('TEBRU PASER DAMAI', 'TEBRU PASER DAMAI'),
            ('TEMPAKAN', 'TEMPAKAN'),
            ('BATU KAJANG', 'BATU KAJANG'),
            ('BUSUI', 'BUSUI'),
            ('KASUNGAI', 'KASUNGAI'),
            ('LEGAI', 'LEGAI'),
            ('RANTAU BUTA', 'RANTAU BUTA'),
            ('RANTAU LAYUNG', 'RANTAU LAYUNG'),
            ('SAMURANGGAU', 'SAMURANGGAU'),
            ('SONGKA', 'SONGKA'),
            ('SUNGAI TERIK', 'SUNGAI TERIK'),
            ('KELUANG PASER JAYA', 'KELUANG PASER JAYA'),
            ('KENDAROM', 'KENDAROM'),
            ('KERTA BUMI', 'KERTA BUMI'),
            ('KLEMPANG SARI', 'KLEMPANG SARI'),
            ('KUARO', 'KUARO'),
            ('LOLO', 'LOLO'),
            ('MODANG', 'MODANG'),
            ('PADANG JAYA', 'PADANG JAYA'),
            ('PASIR MAYANG', 'PASIR MAYANG'),
            ('PONDANG BARU', 'PONDANG BARU'),
            ('RANGAN', 'RANGAN'),
            ('SANDELEY', 'SANDELEY'),
            ('ADANG JAYA', 'ADANG JAYA'),
            ('ATANG PAIT', 'ATANG PAIT'),
            ('BREWE', 'BREWE'),
            ('BUKIT SALOKA', 'BUKIT SALOKA'),
            ('JEMPARING', 'JEMPARING'),
            ('KAYUNGO', 'KAYUNGO'),
            ('KAYUNGO SARI', 'KAYUNGO SARI'),
            ('KERTA BHAKTI', 'KERTA BHAKTI'),
            ('KRAYAN BAHAGIA', 'KRAYAN BAHAGIA'),
            ('KRAYAN JAYA', 'KRAYAN JAYA'),
            ('KRAYAN MAKMUR', 'KRAYAN MAKMUR'),
            ('KRAYAN SENTOSA', 'KRAYAN SENTOSA'),
            ('LOMBOK', 'LOMBOK'),
            ('LONG GELANG', 'LONG GELANG'),
            ('LONG IKIS', 'LONG IKIS'),
            ('MUARA ADANG', 'MUARA ADANG'),
            ('OLUNG', 'OLUNG'),
            ('PAIT', 'PAIT'),
            ('SAMUNTAI', 'SAMUNTAI'),
            ('SAWIT JAYA', 'SAWIT JAYA'),
            ('SEKUROU JAYA', 'SEKUROU JAYA'),
            ('TAJER MULYA', 'TAJER MULYA'),
            ('TAJUR', 'TAJUR'),
            ('TELUK WARU', 'TELUK WARU'),
            ('BENTE TUALAN', 'BENTE TUALAN'),
            ('GUNUNG PUTAR', 'GUNUNG PUTAR'),
            ('KEPALA TELAKE', 'KEPALA TELAKE'),
            ('LONG KALI', 'LONG KALI'),
            ('MARUAT', 'MARUAT'),
            ('MENDIK', 'MENDIK'),
            ('MENDIK BHAKTI', 'MENDIK BHAKTI'),
            ('MENDIK KARYA', 'MENDIK KARYA'),
            ('MENDIK MAKMUR', 'MENDIK MAKMUR'),
            ('MUARA ADANG II', 'MUARA ADANG II'),
            ('MUARA LAMBAKAN', 'MUARA LAMBAKAN'),
            ('MUARA PIAS', 'MUARA PIAS'),
            ('MUARA TELAKE', 'MUARA TELAKE'),
            ('MUARA TOYU', 'MUARA TOYU'),
            ('MUNGGU', 'MUNGGU'),
            ('PERKUWEN', 'PERKUWEN'),
            ('PETIKU', 'PETIKU'),
            ('PINANG JATUS', 'PINANG JATUS'),
            ('PUTANG', 'PUTANG'),
            ('SEBAKUNG', 'SEBAKUNG'),
            ('SEBAKUNG MAKMUR', 'SEBAKUNG MAKMUR'),
            ('SEBAKUNG TAKA', 'SEBAKUNG TAKA'),
            ('BATU BUTOK', 'BATU BUTOK'),
            ('BINANGON', 'BINANGON'),
            ('LONG SAYO', 'LONG SAYO'),
            ('LUSAN', 'LUSAN'),
            ('MUARA KOMAM', 'MUARA KOMAM'),
            ('MUARA KUARO', 'MUARA KUARO'),
            ('MUARA LANGON', 'MUARA LANGON'),
            ('MUARA PAYANG', 'MUARA PAYANG'),
            ('PRAYON', 'PRAYON'),
            ('SEKUAN MAKMUR', 'SEKUAN MAKMUR'),
            ('SWAN SLUTUNG', 'SWAN SLUTUNG'),
            ('UKO', 'UKO'),
            ('BIU', 'BIU'),
            ('LIBUR DINDING', 'LIBUR DINDING'),
            ('LUAN', 'LUAN'),
            ('MUARA ANDEH', 'MUARA ANDEH'),
            ('MUSER', 'MUSER'),
            ('RANTAU ATAS', 'RANTAU ATAS'),
            ('RANTAU BINTUNGAN', 'RANTAU BINTUNGAN'),
            ('SUWETO', 'SUWETO'),
            ('TANJUNG PINANG', 'TANJUNG PINANG'),
            ('BEKOSO', 'BEKOSO'),
            ('DAMIT', 'DAMIT'),
            ('KERESIK BURA', 'KERESIK BURA'),
            ('LABURAN', 'LABURAN'),
            ('LABURAN BARU', 'LABURAN BARU'),
            ('LEMPESU', 'LEMPESU'),
            ('OLONG PINANG', 'OLONG PINANG'),
            ('PASIR BELENGKONG', 'PASIR BELENGKONG'),
            ('SANGKURIMAN', 'SANGKURIMAN'),
            ('SENIUNG JAYA', 'SENIUNG JAYA'),
            ('SUATANG', 'SUATANG'),
            ('SUATANG KETEBAN', 'SUATANG KETEBAN'),
            ('SULILIRAN', 'SULILIRAN'),
            ('SULILIRAN BARU', 'SULILIRAN BARU'),
            ('SUNGE BATU', 'SUNGE BATU'),
            ('JANJU', 'JANJU'),
            ('JONE', 'JONE'),
            ('MUARA PASIR', 'MUARA PASIR'),
            ('PADANG PENGRAPAT', 'PADANG PENGRAPAT'),
            ('PEPARA', 'PEPARA'),
            ('PEREPAT', 'PEREPAT'),
            ('PULAU RANTAU', 'PULAU RANTAU'),
            ('SEMPULANG', 'SEMPULANG'),
            ('SENAKEN', 'SENAKEN'),
            ('SUNGAI LANGIR', 'SUNGAI LANGIR'),
            ('SUNGAI TUAK', 'SUNGAI TUAK'),
            ('TANAH GROGOT', 'TANAH GROGOT'),
            ('TANAH PERIUK', 'TANAH PERIUK'),
            ('TAPIS', 'TAPIS'),
            ('TEPIAN BATANG', 'TEPIAN BATANG'),
            ('KELADEN', 'KELADEN'),
            ('LABUANGKALLO', 'LABUANGKALLO'),
            ('LORI', 'LORI'),
            ('RANDOM', 'RANDOM'),
            ('SELENGOT', 'SELENGOT'),
            ('SENIPAH', 'SENIPAH'),
            ('TANJUNG ARU', 'TANJUNG ARU'),
        )
        widgets = {
            # 'judul': forms.TextInput({'class': 'form-control'}),
            # 'penulis': forms.TextInput({'class': 'form-control'}),
            # 'penerbit': forms.TextInput({'class': 'form-control'}),
            # 'jumlah': forms.NumberInput({'class': 'form-control'}),
            # 'kelompok_id': forms.Select({'class': 'form-control'}),
            'nama_dpt': forms.TextInput({'class': 'form-control'}),
            'kota': forms.Select({'class': 'form-control'}, choices=pilihankota),
            'kecamatan': forms.Select({'class': 'form-control'}, choices=pilihankecamatan),
            'kelurahan': forms.Select({'class': 'form-control'}, choices=pilihankelurahan),
            'alamat': forms.TextInput({'class': 'form-control'}),
            'nik': forms.NumberInput({'class': 'form-control'}),
            'nomor_hp': forms.NumberInput({'class': 'form-control'}),
            'nomor_rekening': forms.NumberInput({'class': 'form-control'}),
            'nomor_kk': forms.NumberInput({'class': 'form-control'}),
            'tanggal_lahir': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_input_data': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_honor': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_telespocheck': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'rt': forms.NumberInput({'class': 'form-control'}),
            'nominal_honor': forms.NumberInput({'class': 'form-control'}),
            'bank': forms.TextInput({'class': 'form-control'}),
            'status_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan_telespocheck': forms.TextInput({'class': 'form-control'}),
            'telespochecker': forms.Select({'class': 'form-control'}),
            'hasil_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan': forms.TextInput({'class': 'form-control'}),
            'nama_pemilik_rekening': forms.TextInput({'class': 'form-control'}),
            'inputer': forms.Select({'class': 'form-control'}),
            'keterangan_honor': forms.TextInput({'class': 'form-control'}),
        }
