from django.forms import ModelForm
from django import forms
from perpustakaan.models import Buku


class FormBuku(ModelForm):
    class Meta:
        model = Buku
        fields = '__all__'
        pilihankota = (
            ('', ''),
            ('SAMARINDA', 'SAMARINDA'),
            ('BALIKPAPAN', 'BALIKPAPAN'),
            ('KUKAR', 'KUKAR'),
            ('BONTANG', 'BONTANG'),
            ('BERAU', 'BERAU'),
            ('KUTAI BARAT', 'KUTAI BARAT'),
            ('KUTAI TIMUR', 'KUTAI TIMUR'),
            ('MAHAKAM ULU', 'MAHAKAM ULU'),
            ('PASER', 'PASER'),
            ('PPU', 'PPU'),
        )
        pilihankecamatan = (
            ('kecamatan', ''),
            ('LOA JANAN ILIR', 'LOA JANAN ILIR'),
            ('PALARAN', 'PALARAN'),
            ('SAMARINDA ILIR', 'SAMARINDA ILIR'),
            ('SAMARINDA KOTA', 'SAMARINDA KOTA'),
            ('SAMARINDA SEBERANG', 'SAMARINDA SEBERANG'),
            ('SAMARINDA ULU', 'SAMARINDA ULU'),
            ('SAMARINDA UTARA', 'SAMARINDA UTARA'),
            ('SAMBUTAN', 'SAMBUTAN'),
            ('SUNGAI KUNJANG', 'SUNGAI KUNJANG'),
            ('SUNGAI PINANG', 'SUNGAI PINANG'),
            ('BALIKPAPAN BARAT', 'BALIKPAPAN BARAT'),
            ('BALIKPAPAN KOTA', 'BALIKPAPAN KOTA'),
            ('BALIKPAPAN SELATAN', 'BALIKPAPAN SELATAN'),
            ('BALIKPAPAN TENGAH', 'BALIKPAPAN TENGAH'),
            ('BALIKPAPAN TIMUR', 'BALIKPAPAN TIMUR'),
            ('BALIKPAPAN UTARA', 'BALIKPAPAN UTARA'),
            ('ANGGANA', 'ANGGANA'),
            ('KEMBANG JANGGUT', 'KEMBANG JANGGUT'),
            ('KENOHAN', 'KENOHAN'),
            ('KOTA BANGUN', 'KOTA BANGUN'),
            ('LOA JANAN', 'LOA JANAN'),
            ('LOA KULU', 'LOA KULU'),
            ('MARANG KAYU', 'MARANG KAYU'),
            ('MUARA BADAK', 'MUARA BADAK'),
            ('MUARA JAWA', 'MUARA JAWA'),
            ('MUARA KAMAN', 'MUARA KAMAN'),
            ('MUARA MUNTAI', 'MUARA MUNTAI'),
            ('MUARA WIS', 'MUARA WIS'),
            ('SAMBOJA', 'SAMBOJA'),
            ('SANGA SANGA', 'SANGA SANGA'),
            ('SEBULU', 'SEBULU'),
            ('TABANG', 'TABANG'),
            ('TENGGARONG', 'TENGGARONG'),
            ('TENGGARONG SEBERANG', 'TENGGARONG SEBERANG'),
            ('BONTANG BARAT', 'BONTANG BARAT'),
            ('BONTANG SELATAN', 'BONTANG SELATAN'),
            ('BONTANG UTARA', 'BONTANG UTARA'),
            ('BATU PUTIH', 'BATU PUTIH'),
            ('BIATAN', 'BIATAN'),
            ('BIDUK-BIDUK', 'BIDUK-BIDUK'),
            ('GUNUNG TABUR', 'GUNUNG TABUR'),
            ('KELAY', 'KELAY'),
            ('MARATUA', 'MARATUA'),
            ('PULAU DERAWAN', 'PULAU DERAWAN'),
            ('SAMBALIUNG', 'SAMBALIUNG'),
            ('SEGAH', 'SEGAH'),
            ('TABALAR', 'TABALAR'),
            ('TALISAYAN', 'TALISAYAN'),
            ('TANJUNG REDEB', 'TANJUNG REDEB'),
            ('TELUK BAYUR', 'TELUK BAYUR'),
            ('BARONG TONGKOK', 'BARONG TONGKOK'),
            ('BENTIAN BESAR', 'BENTIAN BESAR'),
            ('BONGAN', 'BONGAN'),
            ('DAMAI', 'DAMAI'),
            ('JEMPANG', 'JEMPANG'),
            ('LINGGANG BIGUNG', 'LINGGANG BIGUNG'),
            ('LONG IRAM', 'LONG IRAM'),
            ('MELAK', 'MELAK'),
            ('MOOK MANAAR BULATN', 'MOOK MANAAR BULATN'),
            ('MUARA LAWA', 'MUARA LAWA'),
            ('MUARA PAHU', 'MUARA PAHU'),
            ('NYUATAN', 'NYUATAN'),
            ('PENYINGGAHAN', 'PENYINGGAHAN'),
            ('SEKOLAQ DARAT', 'SEKOLAQ DARAT'),
            ('SILUQ NGURAI', 'SILUQ NGURAI'),
            ('TERING', 'TERING'),
            ('BATU AMPAR', 'BATU AMPAR'),
            ('BENGALON', 'BENGALON'),
            ('BUSANG', 'BUSANG'),
            ('KALIORANG', 'KALIORANG'),
            ('KARANGAN', 'KARANGAN'),
            ('KAUBUN', 'KAUBUN'),
            ('KOMBENG', 'KOMBENG'),
            ('LONG MESANGAT', 'LONG MESANGAT'),
            ('MUARA ANCALONG', 'MUARA ANCALONG'),
            ('MUARA BENGKAL', 'MUARA BENGKAL'),
            ('MUARA WAHAU', 'MUARA WAHAU'),
            ('RANTAU PULUNG', 'RANTAU PULUNG'),
            ('SANDARAN', 'SANDARAN'),
            ('SANGATTA SELATAN', 'SANGATTA SELATAN'),
            ('SANGATTA UTARA', 'SANGATTA UTARA'),
            ('SANGKULIRANG', 'SANGKULIRANG'),
            ('TELEN', 'TELEN'),
            ('TELUK PANDAN', 'TELUK PANDAN'),
            ('LAHAM', 'LAHAM'),
            ('LONG APARI', 'LONG APARI'),
            ('LONG BAGUN', 'LONG BAGUN'),
            ('LONG HUBUNG', 'LONG HUBUNG'),
            ('LONG PAHANGAI', 'LONG PAHANGAI'),
            ('BATU ENGAU', 'BATU ENGAU'),
            ('BATU SOPANG', 'BATU SOPANG'),
            ('KUARO', 'KUARO'),
            ('LONG IKIS', 'LONG IKIS'),
            ('LONG KALI', 'LONG KALI'),
            ('MUARA KOMAM', 'MUARA KOMAM'),
            ('MUARA SAMU', 'MUARA SAMU'),
            ('PASIR BALENGKONG', 'PASIR BALENGKONG'),
            ('TANAH GROGOT', 'TANAH GROGOT'),
            ('TANJUNG HARAPAN', 'TANJUNG HARAPAN'),
            ('BABULU', 'BABULU'),
            ('PENAJAM', 'PENAJAM'),
            ('SEPAKU', 'SEPAKU'),
            ('WARU', 'WARU'),
        )
        pilihankelurahan = (
            ('kelurahan', ''),
            ('HARAPAN BARU', 'HARAPAN BARU'),
            ('RAPAK DALAM', 'RAPAK DALAM'),
            ('SENGKOTEK', 'SENGKOTEK'),
            ('SIMPANG TIGA', 'SIMPANG TIGA'),
            ('TANI AMAN', 'TANI AMAN'),
            ('BANTUAS', 'BANTUAS'),
            ('BUKUAN', 'BUKUAN'),
            ('HANDIL BAKTI', 'HANDIL BAKTI'),
            ('RAWA MAKMUR', 'RAWA MAKMUR'),
            ('SIMPANG PASIR', 'SIMPANG PASIR'),
            ('PELITA', 'PELITA'),
            ('SELILI', 'SELILI'),
            ('SIDODAMAI', 'SIDODAMAI'),
            ('SIDOMULYO', 'SIDOMULYO'),
            ('SUNGAI DAMA', 'SUNGAI DAMA'),
            ('BUGIS', 'BUGIS'),
            ('KARANG MUMUS', 'KARANG MUMUS'),
            ('PASAR PAGI', 'PASAR PAGI'),
            ('PELABUHAN', 'PELABUHAN'),
            ('SUNGAI PINANG LUAR', 'SUNGAI PINANG LUAR'),
            ('BAQA', 'BAQA'),
            ('GUNUNG PANJANG', 'GUNUNG PANJANG'),
            ('MANGKUPALAS', 'MANGKUPALAS'),
            ('MESJID', 'MESJID'),
            ('SUNGAI KELEDANG', 'SUNGAI KELEDANG'),
            ('TENUN SAMARINDA', 'TENUN SAMARINDA'),
            ('AIR HITAM', 'AIR HITAM'),
            ('AIR PUTIH', 'AIR PUTIH'),
            ('BUKIT PINANG', 'BUKIT PINANG'),
            ('DADI MULYA', 'DADI MULYA'),
            ('GUNUNG KELUA', 'GUNUNG KELUA'),
            ('JAWA', 'JAWA'),
            ('SIDODADI', 'SIDODADI'),
            ('TELUK LERONG ILIR', 'TELUK LERONG ILIR'),
            ('BUDAYA PAMPANG', 'BUDAYA PAMPANG'),
            ('LEMPAKE', 'LEMPAKE'),
            ('SEMPAJA BARAT', 'SEMPAJA BARAT'),
            ('SEMPAJA SELATAN', 'SEMPAJA SELATAN'),
            ('SEMPAJA TIMUR', 'SEMPAJA TIMUR'),
            ('SEMPAJA UTARA', 'SEMPAJA UTARA'),
            ('SUNGAI SIRING', 'SUNGAI SIRING'),
            ('TANAH MERAH', 'TANAH MERAH'),
            ('MAKROMAN', 'MAKROMAN'),
            ('PULAU ATAS', 'PULAU ATAS'),
            ('SAMBUTAN', 'SAMBUTAN'),
            ('SINDANG SARI', 'SINDANG SARI'),
            ('SUNGAI KAPIH', 'SUNGAI KAPIH'),
            ('KARANG ANYAR', 'KARANG ANYAR'),
            ('KARANG ASAM ILIR', 'KARANG ASAM ILIR'),
            ('KARANG ASAM ULU', 'KARANG ASAM ULU'),
            ('LOA BAKUNG', 'LOA BAKUNG'),
            ('LOA BUAH', 'LOA BUAH'),
            ('LOK BAHU', 'LOK BAHU'),
            ('TELUK LERONG ULU', 'TELUK LERONG ULU'),
            ('BANDARA', 'BANDARA'),
            ('GUNUNG LINGAI', 'GUNUNG LINGAI'),
            ('MUGIREJO', 'MUGIREJO'),
            ('SUNGAI PINANG DALAM', 'SUNGAI PINANG DALAM'),
            ('TEMINDUNG PERMAI', 'TEMINDUNG PERMAI'),
            ('BARU ILIR', 'BARU ILIR'),
            ('BARU TENGAH', 'BARU TENGAH'),
            ('BARU ULU', 'BARU ULU'),
            ('KARIANGAU', 'KARIANGAU'),
            ('MARGA SARI', 'MARGA SARI'),
            ('MARGO MULYO', 'MARGO MULYO'),
            ('DAMAI', 'DAMAI'),
            ('KLANDASAN ILIR', 'KLANDASAN ILIR'),
            ('KLANDASAN ULU', 'KLANDASAN ULU'),
            ('PRAPATAN', 'PRAPATAN'),
            ('TELAGA SARI', 'TELAGA SARI'),
            ('DAMAI BAHAGIA', 'DAMAI BAHAGIA'),
            ('DAMAI BARU', 'DAMAI BARU'),
            ('GUNUNG BAHAGIA', 'GUNUNG BAHAGIA'),
            ('SEPINGGAN', 'SEPINGGAN'),
            ('SEPINGGAN BARU', 'SEPINGGAN BARU'),
            ('SEPINGGAN RAYA', 'SEPINGGAN RAYA'),
            ('SUNGAI NANGKA', 'SUNGAI NANGKA'),
            ('GUNUNG SARI ILIR', 'GUNUNG SARI ILIR'),
            ('GUNUNG SARI ULU', 'GUNUNG SARI ULU'),
            ('KARANG JATI', 'KARANG JATI'),
            ('KARANG REJO', 'KARANG REJO'),
            ('MEKAR SARI', 'MEKAR SARI'),
            ('SUMBER REJO', 'SUMBER REJO'),
            ('LAMARU', 'LAMARU'),
            ('MANGGAR', 'MANGGAR'),
            ('MANGGAR BARU', 'MANGGAR BARU'),
            ('TERITIP', 'TERITIP'),
            ('BATU AMPAR', 'BATU AMPAR'),
            ('GRAHA INDAH', 'GRAHA INDAH'),
            ('GUNUNG SAMARINDA', 'GUNUNG SAMARINDA'),
            ('GUNUNGSAMARINDA BARU', 'GUNUNGSAMARINDA BARU'),
            ('KARANG JOANG', 'KARANG JOANG'),
            ('MUARARAPAK', 'MUARARAPAK'),
            ('ANGGANA', 'ANGGANA'),
            ('HANDIL TERUSAN', 'HANDIL TERUSAN'),
            ('KUTAI LAMA', 'KUTAI LAMA'),
            ('MUARA PANTUAN', 'MUARA PANTUAN'),
            ('SEPATIN', 'SEPATIN'),
            ('SUNGAI MERIAM', 'SUNGAI MERIAM'),
            ('TANI BARU', 'TANI BARU'),
            ('BUKIT LAYANG', 'BUKIT LAYANG'),
            ('GENTING TANAH', 'GENTING TANAH'),
            ('HAMBAU', 'HAMBAU'),
            ('KELEKAT', 'KELEKAT'),
            ('KEMBANG JANGGUT', 'KEMBANG JANGGUT'),
            ('LOA SAKOH', 'LOA SAKOH'),
            ('LONG BELEH HALOQ', 'LONG BELEH HALOQ'),
            ('LONG BELEH MODANG', 'LONG BELEH MODANG'),
            ('MUAI', 'MUAI'),
            ('PERDANA', 'PERDANA'),
            ('PULAU PINANG', 'PULAU PINANG'),
            ('KAHALA', 'KAHALA'),
            ('KAHALA ILIR', 'KAHALA ILIR'),
            ('LAMIN PULUT', 'LAMIN PULUT'),
            ('LAMIN TELIHAN', 'LAMIN TELIHAN'),
            ('SEMAYANG', 'SEMAYANG'),
            ('TELUK BINGKAI', 'TELUK BINGKAI'),
            ('TELUK MUDA', 'TELUK MUDA'),
            ('TUANA TUHA', 'TUANA TUHA'),
            ('TUBUHAN', 'TUBUHAN'),
            ('BENUA BARU', 'BENUA BARU'),
            ('KEDANG IPIL', 'KEDANG IPIL'),
            ('KEDANG MURUNG', 'KEDANG MURUNG'),
            ('KOTA BANGUN I', 'KOTA BANGUN I'),
            ('KOTA BANGUN II', 'KOTA BANGUN II'),
            ('KOTA BANGUN III', 'KOTA BANGUN III'),
            ('KOTA BANGUN ILIR', 'KOTA BANGUN ILIR'),
            ('KOTA BANGUN SEBERANG', 'KOTA BANGUN SEBERANG'),
            ('KOTA BANGUN ULU', 'KOTA BANGUN ULU'),
            ('LIANG', 'LIANG'),
            ('LIANG ULU', 'LIANG ULU'),
            ('LOLENG', 'LOLENG'),
            ('MUHURAN', 'MUHURAN'),
            ('PELA', 'PELA'),
            ('SANGKULIMAN', 'SANGKULIMAN'),
            ('SARI NADI', 'SARI NADI'),
            ('SEBELIMBINGAN', 'SEBELIMBINGAN'),
            ('SEDULANG', 'SEDULANG'),
            ('SUKA BUMI', 'SUKA BUMI'),
            ('SUMBER SARI', 'SUMBER SARI'),
            ('WONOSARI', 'WONOSARI'),
            ('BAKUNGAN', 'BAKUNGAN'),
            ('BATUAH', 'BATUAH'),
            ('LOA DURI ILIR', 'LOA DURI ILIR'),
            ('LOA DURI ULU', 'LOA DURI ULU'),
            ('LOA JANAN ULU', 'LOA JANAN ULU'),
            ('PURWAJAYA', 'PURWAJAYA'),
            ('TANI BHAKTI', 'TANI BHAKTI'),
            ('TANI HARAPAN', 'TANI HARAPAN'),
            ('JEMBAYAN', 'JEMBAYAN'),
            ('JEMBAYAN DALAM', 'JEMBAYAN DALAM'),
            ('JEMBAYAN TENGAH', 'JEMBAYAN TENGAH'),
            ('JONGGON', 'JONGGON'),
            ('JONGKANG', 'JONGKANG'),
            ('KARYA UTAMA', 'KARYA UTAMA'),
            ('LOA KULU KOTA', 'LOA KULU KOTA'),
            ('LOH SUMBER', 'LOH SUMBER'),
            ('LUNG ANAI', 'LUNG ANAI'),
            ('MARGA RAHAYU', 'MARGA RAHAYU'),
            ('PONORAGAN', 'PONORAGAN'),
            ('REMPANGA', 'REMPANGA'),
            ('SEPAKAT', 'SEPAKAT'),
            ('SUNGAI PAYANG', 'SUNGAI PAYANG'),
            ('MAKARTI', 'MAKARTI'),
            ('PERANGAT BARU', 'PERANGAT BARU'),
            ('PERANGAT SELATAN', 'PERANGAT SELATAN'),
            ('SAMBERA BARU', 'SAMBERA BARU'),
            ('SANTAN ULU', 'SANTAN ULU'),
            ('SANTAN ILIR', 'SANTAN ILIR'),
            ('SANTAN TENGAH', 'SANTAN TENGAH'),
            ('BUNGA PUTIH', 'BUNGA PUTIH'),
            ('KERSIK', 'KERSIK'),
            ('SEMANGKO', 'SEMANGKO'),
            ('SEBUNTAL', 'SEBUNTAL'),
            ('BADAK BARU', 'BADAK BARU'),
            ('BADAK MEKAR', 'BADAK MEKAR'),
            ('BATU BATU', 'BATU BATU'),
            ('GAS ALAM BADAK I', 'GAS ALAM BADAK I'),
            ('MUARA BADAK ILIR', 'MUARA BADAK ILIR'),
            ('MUARA BADAK ULU', 'MUARA BADAK ULU'),
            ('SALIKI', 'SALIKI'),
            ('SALO CELLA', 'SALO CELLA'),
            ('SALO PALAI', 'SALO PALAI'),
            ('SUKA DAMAI', 'SUKA DAMAI'),
            ('SUNGAI BAWANG', 'SUNGAI BAWANG'),
            ('TANAH DATAR', 'TANAH DATAR'),
            ('TANJUNG LIMAU', 'TANJUNG LIMAU'),
            ('DONDANG', 'DONDANG'),
            ('MUARA JAWA ILIR', 'MUARA JAWA ILIR'),
            ('MUARA JAWA PESISIR', 'MUARA JAWA PESISIR'),
            ('MUARA JAWA TENGAH', 'MUARA JAWA TENGAH'),
            ('MUARA JAWA ULU', 'MUARA JAWA ULU'),
            ('MUARA KEMBANG', 'MUARA KEMBANG'),
            ('TAMA POLE', 'TAMA POLE'),
            ('TELUK DALAM', 'TELUK DALAM'),
            ('BENUA PUHUN', 'BENUA PUHUN'),
            ('BUKIT JERING', 'BUKIT JERING'),
            ('BUNGA JADI', 'BUNGA JADI'),
            ('CIPARI MAKMUR', 'CIPARI MAKMUR'),
            ('KUPANG BARU', 'KUPANG BARU'),
            ('LEBAHO ULAQ', 'LEBAHO ULAQ'),
            ('LIANG BUAYA', 'LIANG BUAYA'),
            ('MENAMANG KANAN', 'MENAMANG KANAN'),
            ('MENAMANG KIRI', 'MENAMANG KIRI'),
            ('MUARA KAMAN ILIR', 'MUARA KAMAN ILIR'),
            ('MUARA KAMAN ULU', 'MUARA KAMAN ULU'),
            ('MUARA SIRAN', 'MUARA SIRAN'),
            ('PANCA JAYA', 'PANCA JAYA'),
            ('PUAN CEPAK', 'PUAN CEPAK'),
            ('RANTAU HEMPANG', 'RANTAU HEMPANG'),
            ('SABINTULUNG', 'SABINTULUNG'),
            ('SIDOMUKTI', 'SIDOMUKTI'),
            ('TERATAK', 'TERATAK'),
            ('TUNJUNGAN', 'TUNJUNGAN'),
            ('BATUQ', 'BATUQ'),
            ('JANTUR', 'JANTUR'),
            ('JANTUR BARU', 'JANTUR BARU'),
            ('JANTUR SELATAN', 'JANTUR SELATAN'),
            ('KAYU BATU', 'KAYU BATU'),
            ('MUARA ALOH', 'MUARA ALOH'),
            ('MUARA LEKA', 'MUARA LEKA'),
            ('MUARA MUNTAI ILIR', 'MUARA MUNTAI ILIR'),
            ('MUARA MUNTAI ULU', 'MUARA MUNTAI ULU'),
            ('PERIAN', 'PERIAN'),
            ('PULAU HARAPAN', 'PULAU HARAPAN'),
            ('REBAQ RINDING', 'REBAQ RINDING'),
            ('TANJUNG BATUQ HARAPAN', 'TANJUNG BATUQ HARAPAN'),
            ('ENGGELAM', 'ENGGELAM'),
            ('LEBAQ CILANG', 'LEBAQ CILANG'),
            ('LEBAQ MANTAN', 'LEBAQ MANTAN'),
            ('MELINTANG', 'MELINTANG'),
            ('MUARA ENGGELAM', 'MUARA ENGGELAM'),
            ('MUARA WIS', 'MUARA WIS'),
            ('SEBEMBAN', 'SEBEMBAN'),
            ('AMBARAWANG DARAT', 'AMBARAWANG DARAT'),
            ('AMBARAWANG LAUT', 'AMBARAWANG LAUT'),
            ('ARGOSARI', 'ARGOSARI'),
            ('BERINGIN AGUNG', 'BERINGIN AGUNG'),
            ('BUKIT MERDEKA', 'BUKIT MERDEKA'),
            ('BUKIT RAYA', 'BUKIT RAYA'),
            ('HANDIL BARU', 'HANDIL BARU'),
            ('HANDIL BARU DARAT', 'HANDIL BARU DARAT'),
            ('KAMPUNG LAMA', 'KAMPUNG LAMA'),
            ('KARYA JAYA', 'KARYA JAYA'),
            ('KARYA MERDEKA', 'KARYA MERDEKA'),
            ('MARGOMULYO', 'MARGOMULYO'),
            ('MUARA SEMBILANG', 'MUARA SEMBILANG'),
            ('SALOK API DARAT', 'SALOK API DARAT'),
            ('SALOK API LAUT', 'SALOK API LAUT'),
            ('SAMBOJA KUALA', 'SAMBOJA KUALA'),
            ('SANIPAH', 'SANIPAH'),
            ('SUNGAI MERDEKA', 'SUNGAI MERDEKA'),
            ('SUNGAI SELUANG', 'SUNGAI SELUANG'),
            ('TANI BAKTI', 'TANI BAKTI'),
            ('TANJUNG HARAPAN', 'TANJUNG HARAPAN'),
            ('TELUK PEMEDAS', 'TELUK PEMEDAS'),
            ('WONOTIRTO', 'WONOTIRTO'),
            ('PENDINGIN', 'PENDINGIN'),
            ('SANGA-SANGA DALAM', 'SANGA-SANGA DALAM'),
            ('SANGA-SANGA MUARA', 'SANGA-SANGA MUARA'),
            ('SARI JAYA', 'SARI JAYA'),
            ('BELORO', 'BELORO'),
            ('GIRI AGUNG', 'GIRI AGUNG'),
            ('LEKAQ KIDAU', 'LEKAQ KIDAU'),
            ('MANUNGGAL DAYA', 'MANUNGGAL DAYA'),
            ('MEKAR JAYA', 'MEKAR JAYA'),
            ('SANGGULAN', 'SANGGULAN'),
            ('SEBULU ILIR', 'SEBULU ILIR'),
            ('SEBULU MODERN', 'SEBULU MODERN'),
            ('SEBULU ULU', 'SEBULU ULU'),
            ('SEGIHAN', 'SEGIHAN'),
            ('SELERONG', 'SELERONG'),
            ('SENONI', 'SENONI'),
            ('BILA TALANG', 'BILA TALANG'),
            ('BULUK SEN', 'BULUK SEN'),
            ('GUNUNG SARI', 'GUNUNG SARI'),
            ('KAMPUNG BARU', 'KAMPUNG BARU'),
            ('LONG LALANG', 'LONG LALANG'),
            ('MUARA BELINAU', 'MUARA BELINAU'),
            ('MUARA KEBAQ', 'MUARA KEBAQ'),
            ('MUARA PENDOHON', 'MUARA PENDOHON'),
            ('MUARA RITAN', 'MUARA RITAN'),
            ('MUARA SALUNG', 'MUARA SALUNG'),
            ('MUARA TIQ', 'MUARA TIQ'),
            ('MUARA TUBOQ', 'MUARA TUBOQ'),
            ('RITAN BARU', 'RITAN BARU'),
            ('SUDOMULYO', 'SUDOMULYO'),
            ('TABANG LAMA', 'TABANG LAMA'),
            ('TUKUNG RITAN', 'TUKUNG RITAN'),
            ('UMAQ BEKUAY', 'UMAQ BEKUAY'),
            ('UMAQ DIAN', 'UMAQ DIAN'),
            ('UMAQ TUKUNG', 'UMAQ TUKUNG'),
            ('BENDANG RAYA', 'BENDANG RAYA'),
            ('BUKIT BIRU', 'BUKIT BIRU'),
            ('JAHAB', 'JAHAB'),
            ('LOA IPUH', 'LOA IPUH'),
            ('LOA IPUH DARAT', 'LOA IPUH DARAT'),
            ('LOA TEBU', 'LOA TEBU'),
            ('MALUHU', 'MALUHU'),
            ('MANGKURAWANG', 'MANGKURAWANG'),
            ('MELAYU', 'MELAYU'),
            ('PANJI', 'PANJI'),
            ('RAMPAK LAMBUR', 'RAMPAK LAMBUR'),
            ('SUKARAME', 'SUKARAME'),
            ('TIMBAU', 'TIMBAU'),
            ('BANGUN REJO', 'BANGUN REJO'),
            ('BUANA JAYA', 'BUANA JAYA'),
            ('BUKIT PARIAMAN', 'BUKIT PARIAMAN'),
            ('EMBALUT', 'EMBALUT'),
            ('KARANG TUNGGAL', 'KARANG TUNGGAL'),
            ('KERTA BUANA', 'KERTA BUANA'),
            ('LOA LEPU', 'LOA LEPU'),
            ('LOA PARI', 'LOA PARI'),
            ('LOA RAYA', 'LOA RAYA'),
            ('LOA ULUNG', 'LOA ULUNG'),
            ('MANUNGGAL JAYA', 'MANUNGGAL JAYA'),
            ('MULAWARMAN', 'MULAWARMAN'),
            ('PERJIWA', 'PERJIWA'),
            ('SEPARI', 'SEPARI'),
            ('SUKA MAJU', 'SUKA MAJU'),
            ('TANJUNG BATU', 'TANJUNG BATU'),
            ('BELIMBING', 'BELIMBING'),
            ('GUNUNG TELIHAN', 'GUNUNG TELIHAN'),
            ('KANAAN', 'KANAAN'),
            ('BERBAS PANTAI', 'BERBAS PANTAI'),
            ('BERBAS TENGAH', 'BERBAS TENGAH'),
            ('BONTANG LESTARI', 'BONTANG LESTARI'),
            ('SATIMPO', 'SATIMPO'),
            ('TANJUNG LAUT', 'TANJUNG LAUT'),
            ('TANJUNG LAUT INDAH', 'TANJUNG LAUT INDAH'),
            ('API-API', 'API-API'),
            ('BONTANG BARU', 'BONTANG BARU'),
            ('BONTANG KUALA', 'BONTANG KUALA'),
            ('GUNTUNG', 'GUNTUNG'),
            ('GUNUNG ELAI', 'GUNUNG ELAI'),
            ('LOK TUAN', 'LOK TUAN'),
            ('AMPEN MEDANG', 'AMPEN MEDANG'),
            ('BALIKUKUP', 'BALIKUKUP'),
            ('BATU PUTIH', 'BATU PUTIH'),
            ('KAYU INDAH', 'KAYU INDAH'),
            ('LOBANG KELATAK', 'LOBANG KELATAK'),
            ('SUMBER AGUNG', 'SUMBER AGUNG'),
            ('TEMBUDAN', 'TEMBUDAN'),
            ('BIATAN BAPINANG', 'BIATAN BAPINANG'),
            ('BIATAN BARU', 'BIATAN BARU'),
            ('BIATAN ILIR', 'BIATAN ILIR'),
            ('BIATAN LEMPAKE', 'BIATAN LEMPAKE'),
            ('BIATAN ULU', 'BIATAN ULU'),
            ('BUKIT MAKMUR JAYA', 'BUKIT MAKMUR JAYA'),
            ('KARANGAN', 'KARANGAN'),
            ('BIDUK-BIDUK', 'BIDUK-BIDUK'),
            ('GIRING-GIRING', 'GIRING-GIRING'),
            ('PANTAI HARAPAN', 'PANTAI HARAPAN'),
            ('TANJUNG PREPAT', 'TANJUNG PREPAT'),
            ('TELUK SULAIMAN', 'TELUK SULAIMAN'),
            ('TELUK SUMBANG', 'TELUK SUMBANG'),
            ('BATU-BATU', 'BATU-BATU'),
            ('BIRANG', 'BIRANG'),
            ('GUNUNG TABUR', 'GUNUNG TABUR'),
            ('MALUANG', 'MALUANG'),
            ('MELATI JAYA', 'MELATI JAYA'),
            ('MERANCANG ILIR', 'MERANCANG ILIR'),
            ('MERANCANG ULU', 'MERANCANG ULU'),
            ('PULAU BESING', 'PULAU BESING'),
            ('SAMBAKUNGAN', 'SAMBAKUNGAN'),
            ('SAMBURAKAT', 'SAMBURAKAT'),
            ('TASUK', 'TASUK'),
            ('LESAN DAYAK', 'LESAN DAYAK'),
            ('LONG BELIU', 'LONG BELIU'),
            ('LONG DUHUNG', 'LONG DUHUNG'),
            ('LONG KELUH', 'LONG KELUH'),
            ('LONG LAMCIN', 'LONG LAMCIN'),
            ('LONG PELAY', 'LONG PELAY'),
            ('LONG SULUI', 'LONG SULUI'),
            ('MAPULU', 'MAPULU'),
            ('MERABU', 'MERABU'),
            ('MERAPUN', 'MERAPUN'),
            ('MERASA', 'MERASA'),
            ('MUARA LESAN', 'MUARA LESAN'),
            ('PANAAN', 'PANAAN'),
            ('SIDO BANGEN', 'SIDO BANGEN'),
            ('MARATUA BOHESILLAN', 'MARATUA BOHESILLAN'),
            ('MARATUA PAYUNG-PAYUNG', 'MARATUA PAYUNG-PAYUNG'),
            ('MARATUA TELUK ALULU', 'MARATUA TELUK ALULU'),
            ('MARATUA TELUK HARAPAN', 'MARATUA TELUK HARAPAN'),
            ('KASAI', 'KASAI'),
            ('PEGAT BETUMBUK', 'PEGAT BETUMBUK'),
            ('PULAU DERAWAN', 'PULAU DERAWAN'),
            ('TELUK SEMANTING', 'TELUK SEMANTING'),
            ('BENA BARU', 'BENA BARU'),
            ('GURIMBANG', 'GURIMBANG'),
            ('INARAN', 'INARAN'),
            ('LONG LANUK', 'LONG LANUK'),
            ('PEGAT BUKUR', 'PEGAT BUKUR'),
            ('PESAYAN/MENGKAJANG', 'PESAYAN/MENGKAJANG'),
            ('PILANJAU', 'PILANJAU'),
            ('RANTAU PANJANG', 'RANTAU PANJANG'),
            ('SAMBALIUNG', 'SAMBALIUNG'),
            ('SEI BEBANIR BANGUN', 'SEI BEBANIR BANGUN'),
            ('SUARAN', 'SUARAN'),
            ('SUKAN TENGAH', 'SUKAN TENGAH'),
            ('TANJUNG PERANGAT', 'TANJUNG PERANGAT'),
            ('TUMBIK DAYAT', 'TUMBIK DAYAT'),
            ('BATU RAJANG', 'BATU RAJANG'),
            ('BUKIT MAKMUR', 'BUKIT MAKMUR'),
            ('HARAPAN JAYA', 'HARAPAN JAYA'),
            ('LONG AYAN', 'LONG AYAN'),
            ('LONG AYAP', 'LONG AYAP'),
            ('LONG LA AI', 'LONG LA AI'),
            ('PANDAN SARI', 'PANDAN SARI'),
            ('PUNAH SEGAH', 'PUNAH SEGAH'),
            ('PUNAN MAHAKAM', 'PUNAN MAHAKAM'),
            ('PUNAN MALINAU', 'PUNAN MALINAU'),
            ('SIDUUNG INDAH', 'SIDUUNG INDAH'),
            ('TEPIAN BUAH', 'TEPIAN BUAH'),
            ('BAMBANGAN/TUBAAN', 'BAMBANGAN/TUBAAN'),
            ('BUYUNG BUYUNG', 'BUYUNG BUYUNG'),
            ('HARAPAN MAJU', 'HARAPAN MAJU'),
            ('SEMURU', 'SEMURU'),
            ('TABALAR MUARA', 'TABALAR MUARA'),
            ('TABALAR ULU', 'TABALAR ULU'),
            ('BUMU JAYA', 'BUMU JAYA'),
            ('CAMPUR SARI', 'CAMPUR SARI'),
            ('CAPUAK', 'CAPUAK'),
            ('DUMARING', 'DUMARING'),
            ('EKA SAPTA', 'EKA SAPTA'),
            ('PURNASARI JAYA', 'PURNASARI JAYA'),
            ('SUKA MURYA', 'SUKA MURYA'),
            ('SUMBER MULYA', 'SUMBER MULYA'),
            ('TALISAYAN', 'TALISAYAN'),
            ('TUNGGAL BUMI', 'TUNGGAL BUMI'),
            ('GAYAM', 'GAYAM'),
            ('KARANG AMBUN', 'KARANG AMBUN'),
            ('SUNGAI BEDUNGUN', 'SUNGAI BEDUNGUN'),
            ('TENJUNG REDEB', 'TENJUNG REDEB'),
            ('LABANAN JAYA', 'LABANAN JAYA'),
            ('LABANAN MAKARTI', 'LABANAN MAKARTI'),
            ('LABANAN MAKMUR', 'LABANAN MAKMUR'),
            ('RINDING', 'RINDING'),
            ('TELUK BAYUR', 'TELUK BAYUR'),
            ('TUMBIT MELAYU', 'TUMBIT MELAYU'),
            ('ASA', 'ASA'),
            ('BALOK ASA', 'BALOK ASA'),
            ('BARONG TONGKOK', 'BARONG TONGKOK'),
            ('BELEMPUNG ULAQ', 'BELEMPUNG ULAQ'),
            ('ENGKUNI PASEK', 'ENGKUNI PASEK'),
            ('GELEO ASA', 'GELEO ASA'),
            ('GELEO BARU', 'GELEO BARU'),
            ('GEMUHAN ASA', 'GEMUHAN ASA'),
            ('JUAQ ASA', 'JUAQ ASA'),
            ('JUHAN ASA', 'JUHAN ASA'),
            ('MENCIMIN', 'MENCIMIN'),
            ('MUARA ASA', 'MUARA ASA'),
            ('NGENYAN ASA', 'NGENYAN ASA'),
            ('OMBAU ASA', 'OMBAU ASA'),
            ('ONGKO ASA', 'ONGKO ASA'),
            ('PEPAS EHENG', 'PEPAS EHENG'),
            ('PEPES ASA', 'PEPES ASA'),
            ('REJO BASUKI', 'REJO BASUKI'),
            ('SENDAWAR', 'SENDAWAR'),
            ('SIMPANG RAYA', 'SIMPANG RAYA'),
            ('ANAN JAYA', 'ANAN JAYA'),
            ('DILANG PUTI', 'DILANG PUTI'),
            ('JELMU SIBAK', 'JELMU SIBAK'),
            ('PENARUNG', 'PENARUNG'),
            ('RANDA EMPAS', 'RANDA EMPAS'),
            ('SAMBUNG', 'SAMBUNG'),
            ('SUAKONG', 'SUAKONG'),
            ('TENDE', 'TENDE'),
            ('TUKUQ', 'TUKUQ'),
            ('BUKIT HARAPAN', 'BUKIT HARAPAN'),
            ('DERAYA', 'DERAYA'),
            ('GERUNGUNG', 'GERUNGUNG'),
            ('JAMBUK', 'JAMBUK'),
            ('JAMBUK MAKMUR', 'JAMBUK MAKMUR'),
            ('LEMPER', 'LEMPER'),
            ('MUARA GUSIK', 'MUARA GUSIK'),
            ('MUARA KEDANG', 'MUARA KEDANG'),
            ('MUARA SIRAM', 'MUARA SIRAM'),
            ('PENAWAI', 'PENAWAI'),
            ('PERENG TALIQ', 'PERENG TALIQ'),
            ('RESAK', 'RESAK'),
            ('SIRAM JAYA', 'SIRAM JAYA'),
            ('SIRAM MAKMUR', 'SIRAM MAKMUR'),
            ('TANJUNG SARI', 'TANJUNG SARI'),
            ('TANUNG SOKE', 'TANUNG SOKE'),
            ('BENUNG', 'BENUNG'),
            ('BERMAI', 'BERMAI'),
            ('BESIQ', 'BESIQ'),
            ('DAMAI KOTA', 'DAMAI KOTA'),
            ('DAMAI SEBERANG', 'DAMAI SEBERANG'),
            ('JENGAN DANUM', 'JENGAN DANUM'),
            ('KEAY', 'KEAY'),
            ('KELIAN', 'KELIAN'),
            ('LUMPAT DAHUQ', 'LUMPAT DAHUQ'),
            ('MANTAR', 'MANTAR'),
            ('MENDIKA', 'MENDIKA'),
            ('MUARA BOMBOY', 'MUARA BOMBOY'),
            ('MUARA NILIQ', 'MUARA NILIQ'),
            ('MUARA NYAHING', 'MUARA NYAHING'),
            ('MUARA TOKONG', 'MUARA TOKONG'),
            ('SEMPATN', 'SEMPATN'),
            ('TAPULANG', 'TAPULANG'),
            ('BEKOKONG MAKMUR', 'BEKOKONG MAKMUR'),
            ('LEMBONAH', 'LEMBONAH'),
            ('MANCONG', 'MANCONG'),
            ('MUARA NAYAN', 'MUARA NAYAN'),
            ('MUARA OHONG', 'MUARA OHONG'),
            ('MUARA TAE', 'MUARA TAE'),
            ('PENTAT', 'PENTAT'),
            ('PERIGIQ', 'PERIGIQ'),
            ('PULAU LANTING', 'PULAU LANTING'),
            ('TANJUNG ISUY', 'TANJUNG ISUY'),
            ('TANJUNG JAN', 'TANJUNG JAN'),
            ('TANJUNG JONE', 'TANJUNG JONE'),
            ('BANGUN SARI', 'BANGUN SARI'),
            ('BIGUNG BARU', 'BIGUNG BARU'),
            ('LINGGANG AMER', 'LINGGANG AMER'),
            ('LINGGANG BIGUNG', 'LINGGANG BIGUNG'),
            ('LINGGANG KEBUT', 'LINGGANG KEBUT'),
            ('LINGGANG MAPAN', 'LINGGANG MAPAN'),
            ('LINGGANG MELAPEH', 'LINGGANG MELAPEH'),
            ('LINGGANG MENCELEW', 'LINGGANG MENCELEW'),
            ('MELAPEH BARU', 'MELAPEH BARU'),
            ('PURWODADI', 'PURWODADI'),
            ('TUTUNG', 'TUTUNG'),
            ('ANAH', 'ANAH'),
            ('KELIAN LUAR', 'KELIAN LUAR'),
            ('KELIWAI', 'KELIWAI'),
            ('LONG DALIQ', 'LONG DALIQ'),
            ('LONG IRAM BAYAN', 'LONG IRAM BAYAN'),
            ('LONG IRAM ILIR', 'LONG IRAM ILIR'),
            ('LONG IRAM KOTA', 'LONG IRAM KOTA'),
            ('LONG IRAM SEBERANG', 'LONG IRAM SEBERANG'),
            ('MUARA LEBAN', 'MUARA LEBAN'),
            ('SUKOMULYO', 'SUKOMULYO'),
            ('UJOH HALANG', 'UJOH HALANG'),
            ('EMPAKUQ', 'EMPAKUQ'),
            ('EMPAS', 'EMPAS'),
            ('MELAK ILIR', 'MELAK ILIR'),
            ('MELAK ULU', 'MELAK ULU'),
            ('MUARA BENANGAQ', 'MUARA BENANGAQ'),
            ('MUARA BUNYUT', 'MUARA BUNYUT'),
            ('ABIT', 'ABIT'),
            ('GADUR', 'GADUR'),
            ('GEMURUH', 'GEMURUH'),
            ('GUNUNG RAMPAH', 'GUNUNG RAMPAH'),
            ('JENGAN', 'JENGAN'),
            ('KELUMPANG', 'KELUMPANG'),
            ('LINGGANG MARIMUN', 'LINGGANG MARIMUN'),
            ('MERAYAQ', 'MERAYAQ'),
            ('MUARA BATUQ', 'MUARA BATUQ'),
            ('MUARA JAWAQ', 'MUARA JAWAQ'),
            ('MUARA KALAQ', 'MUARA KALAQ'),
            ('REMBAYAN', 'REMBAYAN'),
            ('SAKAQ LOTOQ', 'SAKAQ LOTOQ'),
            ('SAKAQ TADA', 'SAKAQ TADA'),
            ('TONDOH', 'TONDOH'),
            ('BENGGERIS', 'BENGGERIS'),
            ('CEMPEDES', 'CEMPEDES'),
            ('DINGIN', 'DINGIN'),
            ('LAMBING', 'LAMBING'),
            ('LOTAQ', 'LOTAQ'),
            ('MUARA BEGAI', 'MUARA BEGAI'),
            ('MUARA LAWA', 'MUARA LAWA'),
            ('PAYANG', 'PAYANG'),
            ('DASAQ', 'DASAQ'),
            ('GUNUNG BAYAN', 'GUNUNG BAYAN'),
            ('JERANG DAYAK', 'JERANG DAYAK'),
            ('JERANG MELAYU', 'JERANG MELAYU'),
            ('MENDUNG', 'MENDUNG'),
            ('MUARA BAROH', 'MUARA BAROH'),
            ('MUARA BELOAN', 'MUARA BELOAN'),
            ('SEBELANG', 'SEBELANG'),
            ('TANJUNG LAONG', 'TANJUNG LAONG'),
            ('TANJUNG PAGAR', 'TANJUNG PAGAR'),
            ('TELUK TEMPUDAU', 'TELUK TEMPUDAU'),
            ('TEPIAN ULAQ', 'TEPIAN ULAQ'),
            ('AWAI', 'AWAI'),
            ('DEMPAR', 'DEMPAR'),
            ('INTU LINGAU', 'INTU LINGAU'),
            ('JONTAI', 'JONTAI'),
            ('LAKAN BILEM', 'LAKAN BILEM'),
            ("MU'UT", "MU'UT"),
            ('SEMBUAN', 'SEMBUAN'),
            ('SENTALAR', 'SENTALAR'),
            ('TEMULA', 'TEMULA'),
            ('TERAJUK', 'TERAJUK'),
            ('BAKUNG', 'BAKUNG'),
            ('LOA DERAS', 'LOA DERAS'),
            ('MINTA', 'MINTA'),
            ('PENYINGGAHAN ILIR', 'PENYINGGAHAN ILIR'),
            ('PENYINGGAHAN ULU', 'PENYINGGAHAN ULU'),
            ('TANJUNG HAUR', 'TANJUNG HAUR'),
            ('LELENG', 'LELENG'),
            ('SEKOLAQ DARAT', 'SEKOLAQ DARAT'),
            ('SEKOLAQ JOLEQ', 'SEKOLAQ JOLEQ'),
            ('SEKOLAQ MULIAQ', 'SEKOLAQ MULIAQ'),
            ('SEKOLAQ ODAY', 'SEKOLAQ ODAY'),
            ('SRIMULYO', 'SRIMULYO'),
            ('SUMBER BANGUN', 'SUMBER BANGUN'),
            ('BENTAS', 'BENTAS'),
            ('BETUNG', 'BETUNG'),
            ('KALIQ', 'KALIQ'),
            ('KENDISIQ', 'KENDISIQ'),
            ('KENYANYAN', 'KENYANYAN'),
            ('KIAQ', 'KIAQ'),
            ('LENDIAN LIANG NAYUQ', 'LENDIAN LIANG NAYUQ'),
            ('MUARA KELAWIT', 'MUARA KELAWIT'),
            ('MUARA PONAQ', 'MUARA PONAQ'),
            ('MUHUR', 'MUHUR'),
            ('PENAWANG', 'PENAWANG'),
            ('RIKONG', 'RIKONG'),
            ('SANG-SANG', 'SANG-SANG'),
            ('TANAH MEA', 'TANAH MEA'),
            ('TEBISAQ', 'TEBISAQ'),
            ('TENDIQ', 'TENDIQ'),
            ('BANJAREJO', 'BANJAREJO'),
            ('GABUNG BARU', 'GABUNG BARU'),
            ('JELEMUQ', 'JELEMUQ'),
            ('KELIAN DALAM', 'KELIAN DALAM'),
            ('KELUBAQ', 'KELUBAQ'),
            ('MUARA MUJAN', 'MUARA MUJAN'),
            ('MUYUB AKET', 'MUYUB AKET'),
            ('MUYUB ILIR', 'MUYUB ILIR'),
            ('MUYUB ULU', 'MUYUB ULU'),
            ('PURWOREJO', 'PURWOREJO'),
            ('TERING BARU', 'TERING BARU'),
            ('TERING LAMA', 'TERING LAMA'),
            ('TERING LAMA ULU', 'TERING LAMA ULU'),
            ('TERING SEBERANG', 'TERING SEBERANG'),
            ('TUKUL', 'TUKUL'),
            ('BATU TIMBAU', 'BATU TIMBAU'),
            ('BATU TIMBAU ULU', 'BATU TIMBAU ULU'),
            ('BENO HARAPAN', 'BENO HARAPAN'),
            ('HIMBA LESTARI', 'HIMBA LESTARI'),
            ('MAWAI INDAH', 'MAWAI INDAH'),
            ('MUGI RAHAYU', 'MUGI RAHAYU'),
            ('TELAGA', 'TELAGA'),
            ('KERAITAN', 'KERAITAN'),
            ('MUARA BENGALON', 'MUARA BENGALON'),
            ('SEKERAT', 'SEKERAT'),
            ('SEPASO', 'SEPASO'),
            ('SEPASO BARAT', 'SEPASO BARAT'),
            ('SEPASO SELATAN', 'SEPASO SELATAN'),
            ('SEPASO TIMUR', 'SEPASO TIMUR'),
            ('TEBANGAN LEBAK', 'TEBANGAN LEBAK'),
            ('TEPIAN BARU', 'TEPIAN BARU'),
            ('TEPIAN INDAH', 'TEPIAN INDAH'),
            ('TEPIAN LANGSAT', 'TEPIAN LANGSAT'),
            ('LONG BETUQ', 'LONG BETUQ'),
            ('LONG LEES', 'LONG LEES'),
            ('LONG NYELONG', 'LONG NYELONG'),
            ('LONG PEJENG', 'LONG PEJENG'),
            ('MEKAR BARU', 'MEKAR BARU'),
            ('MENDOM', 'MENDOM'),
            ('RANTAU SENTOSA', 'RANTAU SENTOSA'),
            ('BANGUN JAYA', 'BANGUN JAYA'),
            ('BUMI SEJAHTERA', 'BUMI SEJAHTERA'),
            ('CITRA MANUNGGAL JAYA', 'CITRA MANUNGGAL JAYA'),
            ('KALIORANG', 'KALIORANG'),
            ('SELANGKAU', 'SELANGKAU'),
            ("BA'AY", "BA'AY"),
            ('BATU LEPOQ', 'BATU LEPOQ'),
            ('KARANGAN DALAM', 'KARANGAN DALAM'),
            ('KARANGAN HILIR', 'KARANGAN HILIR'),
            ('KARANGAN SEBERANG', 'KARANGAN SEBERANG'),
            ('MUKTI LESTARI', 'MUKTI LESTARI'),
            ('PENGADAN', 'PENGADAN'),
            ('BUKIT PERMATA', 'BUKIT PERMATA'),
            ('BUMI ETAM', 'BUMI ETAM'),
            ('BUMI JAYA', 'BUMI JAYA'),
            ('BUMI RAPAK', 'BUMI RAPAK'),
            ('CIPTA GRAHA', 'CIPTA GRAHA'),
            ('KADUNGAN JAYA', 'KADUNGAN JAYA'),
            ('MATA AIR', 'MATA AIR'),
            ('PENGADAN BARU', 'PENGADAN BARU'),
            ('KOMBENG INDAH', 'KOMBENG INDAH'),
            ('MAKMUR JAYA', 'MAKMUR JAYA'),
            ('MARGA MULYA', 'MARGA MULYA'),
            ('MIAU BARU', 'MIAU BARU'),
            ('SRI PANTUN', 'SRI PANTUN'),
            ('SUKAMAJU', 'SUKAMAJU'),
            ('MELAN', 'MELAN'),
            ('MUKTI UTAMA', 'MUKTI UTAMA'),
            ('SEGOI MAKMUR', 'SEGOI MAKMUR'),
            ('SIKA MAKMUR', 'SIKA MAKMUR'),
            ('TANAH ABANG', 'TANAH ABANG'),
            ('GEMAR BARU', 'GEMAR BARU'),
            ('KELINJAU ILIR', 'KELINJAU ILIR'),
            ('KELINJAU ULU', 'KELINJAU ULU'),
            ('LONG NAH', 'LONG NAH'),
            ('LONG POQ BARU', 'LONG POQ BARU'),
            ('LONG TESAK', 'LONG TESAK'),
            ('MUARA DUN', 'MUARA DUN'),
            ('SENYIUR', 'SENYIUR'),
            ('TELUK BARU', 'TELUK BARU'),
            ('BATU BALAI', 'BATU BALAI'),
            ('MUARA BENGKAL ILIR', 'MUARA BENGKAL ILIR'),
            ('MUARA BENGKAL ULU', 'MUARA BENGKAL ULU'),
            ('MULUPAN', 'MULUPAN'),
            ('NGAYAU', 'NGAYAU'),
            ('SENAMBAH', 'SENAMBAH'),
            ('BENHES', 'BENHES'),
            ('DABEQ', 'DABEQ'),
            ('DIAQ LAY', 'DIAQ LAY'),
            ('JUK LUAY', 'JUK LUAY'),
            ('KARYA BHAKTI', 'KARYA BHAKTI'),
            ('LONG WEHEA', 'LONG WEHEA'),
            ('MUARA WAHAU', 'MUARA WAHAU'),
            ('NEHES LIAH BING', 'NEHES LIAH BING'),
            ('WAHAU BARU', 'WAHAU BARU'),
            ('WANASARI', 'WANASARI'),
            ('KEBON AGUNG', 'KEBON AGUNG'),
            ('MASALAP RAYA', 'MASALAP RAYA'),
            ('MUKTI JAYA', 'MUKTI JAYA'),
            ('PULUNG SARI', 'PULUNG SARI'),
            ('RANTAU MAKMUR', 'RANTAU MAKMUR'),
            ('TANJUNG LABU', 'TANJUNG LABU'),
            ('TEPIAN MAKMUR', 'TEPIAN MAKMUR'),
            ('MANUBAR', 'MANUBAR'),
            ('MANUBAR DALAM', 'MANUBAR DALAM'),
            ('MARUKANGAN', 'MARUKANGAN'),
            ('SANDARAN', 'SANDARAN'),
            ('SUSUK DALAM', 'SUSUK DALAM'),
            ('SUSUK LUAR', 'SUSUK LUAR'),
            ('SUSUK TENGAH', 'SUSUK TENGAH'),
            ('TADOAN', 'TADOAN'),
            ('TANJUNG MANGKALIHAT', 'TANJUNG MANGKALIHAT'),
            ('SANGATTA SELATAN', 'SANGATTA SELATAN'),
            ('SANGKIMA', 'SANGKIMA'),
            ('SANGKIMA LAMA', 'SANGKIMA LAMA'),
            ('SINGA GEWEH', 'SINGA GEWEH'),
            ('SANGATTA UTARA', 'SANGATTA UTARA'),
            ('SINGA GEMBARA', 'SINGA GEMBARA'),
            ('SWARGA BARA', 'SWARGA BARA'),
            ('TELUK LINGGA', 'TELUK LINGGA'),
            ('PINANG RAYA', 'PINANG RAYA'),
            ('BENUA BARU ILIR', 'BENUA BARU ILIR'),
            ('BENUA BARU ULU', 'BENUA BARU ULU'),
            ('KERAYAAN', 'KERAYAAN'),
            ('KOLEK', 'KOLEK'),
            ('MALOY', 'MALOY'),
            ('MANDAU PANTAI SEJAHTERA', 'MANDAU PANTAI SEJAHTERA'),
            ('MANDU DALAM', 'MANDU DALAM'),
            ('PELAWAN', 'PELAWAN'),
            ('PERIDAN', 'PERIDAN'),
            ('PERUPUK', 'PERUPUK'),
            ('PULAU MIANG', 'PULAU MIANG'),
            ('SAQA', 'SAQA'),
            ('SEMPAYAU', 'SEMPAYAU'),
            ('TANJUNG MANIS', 'TANJUNG MANIS'),
            ('TEPIAN TARAP', 'TEPIAN TARAP'),
            ('JUK AYAQ', 'JUK AYAQ'),
            ('KERNYANYAN', 'KERNYANYAN'),
            ('LONG MELAH', 'LONG MELAH'),
            ('LONG NORAN', 'LONG NORAN'),
            ('LONG SEGAR', 'LONG SEGAR'),
            ('MARAH HALOQ', 'MARAH HALOQ'),
            ('MUARA PANTUN', 'MUARA PANTUN'),
            ('DANAU REDAN', 'DANAU REDAN'),
            ('KANDOLO', 'KANDOLO'),
            ('MARTADINATA', 'MARTADINATA'),
            ('SUKA RAHMAT', 'SUKA RAHMAT'),
            ('TELUK PANDAN', 'TELUK PANDAN'),
            ('DANUM PAROY', 'DANUM PAROY'),
            ('LAHAM', 'LAHAM'),
            ('LONG GELAWANG', 'LONG GELAWANG'),
            ('MUARA RATAH', 'MUARA RATAH'),
            ('NYARIBUNGAN', 'NYARIBUNGAN'),
            ('LONG APARI', 'LONG APARI'),
            ('LONG KERIOQ', 'LONG KERIOQ'),
            ('LONG PENANEH I', 'LONG PENANEH I'),
            ('LONG PENANEH II', 'LONG PENANEH II'),
            ('LONG PENANEH III', 'LONG PENANEH III'),
            ('NAHA BUAN', 'NAHA BUAN'),
            ('NAHA SILAT', 'NAHA SILAT'),
            ('NAHA TIFAB', 'NAHA TIFAB'),
            ("TIONG BU'U", "TIONG BU'U"),
            ('TIONG OHANG', 'TIONG OHANG'),
            ('BATOQ KELO', 'BATOQ KELO'),
            ('BATU MAJANG', 'BATU MAJANG'),
            ('LONG BAGUN ILIR', 'LONG BAGUN ILIR'),
            ('LONG BAGUN ULU', 'LONG BAGUN ULU'),
            ('LONG HURAI', 'LONG HURAI'),
            ('LONG MELAHAM', 'LONG MELAHAM'),
            ('LONG MERAH', 'LONG MERAH'),
            ('MEMAHAK BESAR', 'MEMAHAK BESAR'),
            ('MEMAHAK ULU', 'MEMAHAK ULU'),
            ('RUKUN DAMAI', 'RUKUN DAMAI'),
            ('UJOH BILANG', 'UJOH BILANG'),
            ('DATAH BILANG BARU', 'DATAH BILANG BARU'),
            ('DATAH BILANG ILIR', 'DATAH BILANG ILIR'),
            ('DATAH BILANG ULU', 'DATAH BILANG ULU'),
            ('LONG HUBUNG', 'LONG HUBUNG'),
            ('LONG HUBUNG ULU', 'LONG HUBUNG ULU'),
            ('LUTAN', 'LUTAN'),
            ('MATALIBAQ', 'MATALIBAQ'),
            ('MEMAHAK TEBOQ', 'MEMAHAK TEBOQ'),
            ('SIRAU', 'SIRAU'),
            ('TRI PARIQ MAKMUR', 'TRI PARIQ MAKMUR'),
            ('WANA PARIQ', 'WANA PARIQ'),
            ('DATAH NAHA', 'DATAH NAHA'),
            ('DELANG KEROHONG', 'DELANG KEROHONG'),
            ('LIRUNG UBING', 'LIRUNG UBING'),
            ('LIU MULANG', 'LIU MULANG'),
            ('LONG ISUN', 'LONG ISUN'),
            ('LONG LUNUK', 'LONG LUNUK'),
            ('LONG LUNUK BARU', 'LONG LUNUK BARU'),
            ('LONG PAHANGAI I', 'LONG PAHANGAI I'),
            ('LONG PAHANGAI II', 'LONG PAHANGAI II'),
            ('LONG PAKAQ', 'LONG PAKAQ'),
            ('LONG PAKAQ BARU', 'LONG PAKAQ BARU'),
            ('LONG TUYOQ', 'LONG TUYOQ'),
            ('NAHA ARU', 'NAHA ARU'),
            ('BAI JAYA', 'BAI JAYA'),
            ('KERANG', 'KERANG'),
            ('KERANG DAYO', 'KERANG DAYO'),
            ('LANGGAI', 'LANGGAI'),
            ('LOMU', 'LOMU'),
            ('MENGKUDU', 'MENGKUDU'),
            ('PENGGUREN JAYA', 'PENGGUREN JAYA'),
            ('PETANGIS', 'PETANGIS'),
            ('RIWANG', 'RIWANG'),
            ('SAING PRUPUK', 'SAING PRUPUK'),
            ('SEGENDANG', 'SEGENDANG'),
            ('TEBRU PASER DAMAI', 'TEBRU PASER DAMAI'),
            ('TEMPAKAN', 'TEMPAKAN'),
            ('BATU KAJANG', 'BATU KAJANG'),
            ('BUSUI', 'BUSUI'),
            ('KASUNGAI', 'KASUNGAI'),
            ('LEGAI', 'LEGAI'),
            ('RANTAU BUTA', 'RANTAU BUTA'),
            ('RANTAU LAYUNG', 'RANTAU LAYUNG'),
            ('SAMURANGGAU', 'SAMURANGGAU'),
            ('SONGKA', 'SONGKA'),
            ('SUNGAI TERIK', 'SUNGAI TERIK'),
            ('KELUANG PASER JAYA', 'KELUANG PASER JAYA'),
            ('KENDAROM', 'KENDAROM'),
            ('KERTA BUMI', 'KERTA BUMI'),
            ('KLEMPANG SARI', 'KLEMPANG SARI'),
            ('KUARO', 'KUARO'),
            ('LOLO', 'LOLO'),
            ('MODANG', 'MODANG'),
            ('PADANG JAYA', 'PADANG JAYA'),
            ('PASIR MAYANG', 'PASIR MAYANG'),
            ('PONDANG BARU', 'PONDANG BARU'),
            ('RANGAN', 'RANGAN'),
            ('SANDELEY', 'SANDELEY'),
            ('ADANG JAYA', 'ADANG JAYA'),
            ('ATANG PAIT', 'ATANG PAIT'),
            ('BREWE', 'BREWE'),
            ('BUKIT SALOKA', 'BUKIT SALOKA'),
            ('JEMPARING', 'JEMPARING'),
            ('KAYUNGO', 'KAYUNGO'),
            ('KAYUNGO SARI', 'KAYUNGO SARI'),
            ('KERTA BHAKTI', 'KERTA BHAKTI'),
            ('KRAYAN BAHAGIA', 'KRAYAN BAHAGIA'),
            ('KRAYAN JAYA', 'KRAYAN JAYA'),
            ('KRAYAN MAKMUR', 'KRAYAN MAKMUR'),
            ('KRAYAN SENTOSA', 'KRAYAN SENTOSA'),
            ('LOMBOK', 'LOMBOK'),
            ('LONG GELANG', 'LONG GELANG'),
            ('LONG IKIS', 'LONG IKIS'),
            ('MUARA ADANG', 'MUARA ADANG'),
            ('OLUNG', 'OLUNG'),
            ('PAIT', 'PAIT'),
            ('SAMUNTAI', 'SAMUNTAI'),
            ('SAWIT JAYA', 'SAWIT JAYA'),
            ('SEKUROU JAYA', 'SEKUROU JAYA'),
            ('TAJER MULYA', 'TAJER MULYA'),
            ('TAJUR', 'TAJUR'),
            ('TELUK WARU', 'TELUK WARU'),
            ('BENTE TUALAN', 'BENTE TUALAN'),
            ('GUNUNG PUTAR', 'GUNUNG PUTAR'),
            ('KEPALA TELAKE', 'KEPALA TELAKE'),
            ('LONG KALI', 'LONG KALI'),
            ('MARUAT', 'MARUAT'),
            ('MENDIK', 'MENDIK'),
            ('MENDIK BHAKTI', 'MENDIK BHAKTI'),
            ('MENDIK KARYA', 'MENDIK KARYA'),
            ('MENDIK MAKMUR', 'MENDIK MAKMUR'),
            ('MUARA ADANG II', 'MUARA ADANG II'),
            ('MUARA LAMBAKAN', 'MUARA LAMBAKAN'),
            ('MUARA PIAS', 'MUARA PIAS'),
            ('MUARA TELAKE', 'MUARA TELAKE'),
            ('MUARA TOYU', 'MUARA TOYU'),
            ('MUNGGU', 'MUNGGU'),
            ('PERKUWEN', 'PERKUWEN'),
            ('PETIKU', 'PETIKU'),
            ('PINANG JATUS', 'PINANG JATUS'),
            ('PUTANG', 'PUTANG'),
            ('SEBAKUNG', 'SEBAKUNG'),
            ('SEBAKUNG MAKMUR', 'SEBAKUNG MAKMUR'),
            ('SEBAKUNG TAKA', 'SEBAKUNG TAKA'),
            ('BATU BUTOK', 'BATU BUTOK'),
            ('BINANGON', 'BINANGON'),
            ('LONG SAYO', 'LONG SAYO'),
            ('LUSAN', 'LUSAN'),
            ('MUARA KOMAM', 'MUARA KOMAM'),
            ('MUARA KUARO', 'MUARA KUARO'),
            ('MUARA LANGON', 'MUARA LANGON'),
            ('MUARA PAYANG', 'MUARA PAYANG'),
            ('PRAYON', 'PRAYON'),
            ('SEKUAN MAKMUR', 'SEKUAN MAKMUR'),
            ('SWAN SLUTUNG', 'SWAN SLUTUNG'),
            ('UKO', 'UKO'),
            ('BIU', 'BIU'),
            ('LIBUR DINDING', 'LIBUR DINDING'),
            ('LUAN', 'LUAN'),
            ('MUARA ANDEH', 'MUARA ANDEH'),
            ('MUSER', 'MUSER'),
            ('RANTAU ATAS', 'RANTAU ATAS'),
            ('RANTAU BINTUNGAN', 'RANTAU BINTUNGAN'),
            ('SUWETO', 'SUWETO'),
            ('TANJUNG PINANG', 'TANJUNG PINANG'),
            ('BEKOSO', 'BEKOSO'),
            ('DAMIT', 'DAMIT'),
            ('KERESIK BURA', 'KERESIK BURA'),
            ('LABURAN', 'LABURAN'),
            ('LABURAN BARU', 'LABURAN BARU'),
            ('LEMPESU', 'LEMPESU'),
            ('OLONG PINANG', 'OLONG PINANG'),
            ('PASIR BELENGKONG', 'PASIR BELENGKONG'),
            ('SANGKURIMAN', 'SANGKURIMAN'),
            ('SENIUNG JAYA', 'SENIUNG JAYA'),
            ('SUATANG', 'SUATANG'),
            ('SUATANG KETEBAN', 'SUATANG KETEBAN'),
            ('SULILIRAN', 'SULILIRAN'),
            ('SULILIRAN BARU', 'SULILIRAN BARU'),
            ('SUNGE BATU', 'SUNGE BATU'),
            ('JANJU', 'JANJU'),
            ('JONE', 'JONE'),
            ('MUARA PASIR', 'MUARA PASIR'),
            ('PADANG PENGRAPAT', 'PADANG PENGRAPAT'),
            ('PEPARA', 'PEPARA'),
            ('PEREPAT', 'PEREPAT'),
            ('PULAU RANTAU', 'PULAU RANTAU'),
            ('SEMPULANG', 'SEMPULANG'),
            ('SENAKEN', 'SENAKEN'),
            ('SUNGAI LANGIR', 'SUNGAI LANGIR'),
            ('SUNGAI TUAK', 'SUNGAI TUAK'),
            ('TANAH GROGOT', 'TANAH GROGOT'),
            ('TANAH PERIUK', 'TANAH PERIUK'),
            ('TAPIS', 'TAPIS'),
            ('TEPIAN BATANG', 'TEPIAN BATANG'),
            ('KELADEN', 'KELADEN'),
            ('LABUANGKALLO', 'LABUANGKALLO'),
            ('LORI', 'LORI'),
            ('RANDOM', 'RANDOM'),
            ('SELENGOT', 'SELENGOT'),
            ('SENIPAH', 'SENIPAH'),
            ('TANJUNG ARU', 'TANJUNG ARU'),
            ('BABULU DARAT', 'BABULU DARAT'),
            ('BABULU LAUT', 'BABULU LAUT'),
            ('GUNUNG INTAN', 'GUNUNG INTAN'),
            ('GUNUNG MAKMUR', 'GUNUNG MAKMUR'),
            ('GUNUNG MULIA', 'GUNUNG MULIA'),
            ('LABANGKA', 'LABANGKA'),
            ('LABANGKA BARAT', 'LABANGKA BARAT'),
            ('RAWA MULIA', 'RAWA MULIA'),
            ('RINTIK', 'RINTIK'),
            ('SEBAKUNG JAYA', 'SEBAKUNG JAYA'),
            ('SRI RAHARJA', 'SRI RAHARJA'),
            ('BUKIT SUBUR', 'BUKIT SUBUR'),
            ('BULUMINUNG', 'BULUMINUNG'),
            ('GERSIK', 'GERSIK'),
            ('GIRI MUKTI', 'GIRI MUKTI'),
            ('GIRIPURWA', 'GIRIPURWA'),
            ('GUNUNG SETELENG', 'GUNUNG SETELENG'),
            ('JENEBORA', 'JENEBORA'),
            ('LAWE-LAWE', 'LAWE-LAWE'),
            ('NENANG', 'NENANG'),
            ('NIPAH-NIPAH', 'NIPAH-NIPAH'),
            ('PANTAI LANGO', 'PANTAI LANGO'),
            ('PEJALA', 'PEJALA'),
            ('PENAJAM', 'PENAJAM'),
            ('PETUNG', 'PETUNG'),
            ('RIKO', 'RIKO'),
            ('SALO LOANG', 'SALO LOANG'),
            ('SEPAN', 'SEPAN'),
            ('SESUMPU', 'SESUMPU'),
            ('SIDOREJO', 'SIDOREJO'),
            ('SOTEK', 'SOTEK'),
            ('SUNGAI PARIT', 'SUNGAI PARIT'),
            ('TANJUNG TENGAH', 'TANJUNG TENGAH'),
            ('ARGO MULYO', 'ARGO MULYO'),
            ('BINUANG', 'BINUANG'),
            ('BUMI HARAPAN', 'BUMI HARAPAN'),
            ('KARANG JINAWI', 'KARANG JINAWI'),
            ('MARIDAN', 'MARIDAN'),
            ('MENTAWIR', 'MENTAWIR'),
            ('PEMALUAN', 'PEMALUAN'),
            ('SEMOI DUA', 'SEMOI DUA'),
            ('SEPAKU', 'SEPAKU'),
            ('SUKA RAJA', 'SUKA RAJA'),
            ('SUKO MULYO', 'SUKO MULYO'),
            ('TELEMOW', 'TELEMOW'),
            ('TENGIN BARU', 'TENGIN BARU'),
            ('WONO SARI', 'WONO SARI'),
            ('BANGUN MULYA', 'BANGUN MULYA'),
            ('SESULU', 'SESULU'),
            ('WARU', 'WARU'),
        )
        widgets = {
            # 'judul': forms.TextInput({'class': 'form-control'}),
            # 'penulis': forms.TextInput({'class': 'form-control'}),
            # 'penerbit': forms.TextInput({'class': 'form-control'}),
            # 'jumlah': forms.NumberInput({'class': 'form-control'}),
            # 'kelompok_id': forms.Select({'class': 'form-control'}),
            'nama_dpt': forms.TextInput({'class': 'form-control'}),
            'kota': forms.Select({'class': 'form-control'}, choices=pilihankota),
            'kecamatan': forms.Select({'class': 'form-control'}, choices=pilihankecamatan),
            'kelurahan': forms.Select({'class': 'form-control'}, choices=pilihankelurahan),
            'alamat': forms.TextInput({'class': 'form-control'}),
            'nik': forms.NumberInput({'class': 'form-control'}),
            'nomor_hp': forms.NumberInput({'class': 'form-control'}),
            'nomor_rekening': forms.NumberInput({'class': 'form-control'}),
            'nomor_kk': forms.NumberInput({'class': 'form-control'}),
            'tanggal_lahir': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_input_data': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_honor': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'tanggal_telespocheck': forms.DateInput({'class': 'form-control', 'type': 'date'}),
            'rt': forms.NumberInput({'class': 'form-control'}),
            'nominal_honor': forms.NumberInput({'class': 'form-control'}),
            'bank': forms.TextInput({'class': 'form-control'}),
            'status_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan_telespocheck': forms.TextInput({'class': 'form-control'}),
            'telespochecker': forms.Select({'class': 'form-control'}),
            'hasil_telespocheck': forms.Select({'class': 'form-control'}),
            'keterangan': forms.TextInput({'class': 'form-control'}),
            'nama_pemilik_rekening': forms.TextInput({'class': 'form-control'}),
            'inputer': forms.Select({'class': 'form-control'}),
            'keterangan_honor': forms.TextInput({'class': 'form-control'}),
        }
